version: '3.9'

services:
  db:
    image: postgres:15
    container_name: selforg_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - selforg_net

  api:
    image: ${YCR_REGISTRY}/${YCR_IMAGE_NAME}:${IMAGE_TAG}
    container_name: selforg_api
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: "5432"
      PRODUCTION_MODE: "true"
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PASSWORD_SECRET_KEY: ${PASSWORD_SECRET_KEY}
      JWT_LIFE_TIME_SECONDS: "3600"
      COOKIE_TOKEN_NAME: ${COOKIE_TOKEN_NAME}
      HOST: "0.0.0.0"
      PORT: "8000"
      FRONT_HOST: ${FRONT_HOST}
      FRONT_PORT: ${FRONT_PORT}
    ports:
      - "8000:8000"
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always
    networks:
      - selforg_net

volumes:
  pgdata:

networks:
  selforg_net:
    external: true
    name: selforg_net

