class TableName:
    USER = 'user'
    COMMUNITY_SETTINGS = 'community_settings'
    COMMUNITY = 'community'
    INITIATIVE = 'initiative'
    INITIATIVE_CATEGORY = 'initiative_category'
    INITIATIVE_TYPE = 'initiative_type'
    STATUS = 'status'
    RESULT_VOTING = 'result_voting'
    DELEGATE_SETTINGS = 'delegate_settings'
    RELATION_CS_CATEGORIES = 'relation_cs_categories'
    RELATION_CS_DS = 'relation_cs_ds'
    RELATION_DS_USERS = 'relation_ds_users'
    RELATION_INITIATIVE_RV = 'relation_initiative_voting_results'
