"""Fix RequestMember table

Revision ID: 0468d9240592
Revises: 475977a678c3
Create Date: 2024-08-31 21:59:23.232605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0468d9240592'
down_revision: Union[str, None] = '475977a678c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_member', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_member', 'is_blocked')
    # ### end Alembic commands ###
