"""update request member table

Revision ID: 0b69f9d88d87
Revises: d23b6d1d64ae
Create Date: 2024-04-28 13:27:43.215651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b69f9d88d87'
down_revision: Union[str, None] = 'd23b6d1d64ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_member', sa.Column('parent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_member', 'parent_id')
    # ### end Alembic commands ###
