"""init commit

Revision ID: 0bc6834e1799
Revises: 
Create Date: 2025-04-13 04:04:30.163456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc6834e1799'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('about_me', sa.String(), nullable=True),
    sa.Column('foto_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('community_description',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value', 'community_id', name='idx_unique_community_description_id')
    )
    op.create_index(op.f('ix_community_description_creator_id'), 'community_description', ['creator_id'], unique=False)
    op.create_index(op.f('ix_community_description_value'), 'community_description', ['value'], unique=False)
    op.create_table('community_name',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'community_id', name='idx_unique_community_name_id')
    )
    op.create_index(op.f('ix_community_name_community_id'), 'community_name', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_name_creator_id'), 'community_name', ['creator_id'], unique=False)
    op.create_table('file_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('mimetype', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noncompliance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_noncompliance_community_id'), 'noncompliance', ['community_id'], unique=False)
    op.create_index(op.f('ix_noncompliance_creator_id'), 'noncompliance', ['creator_id'], unique=False)
    op.create_table('responsibility',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsibility_community_id'), 'responsibility', ['community_id'], unique=False)
    op.create_index(op.f('ix_responsibility_creator_id'), 'responsibility', ['creator_id'], unique=False)
    op.create_table('solution',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_creator_id'), 'solution', ['creator_id'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voting_option',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_multi_select', sa.Boolean(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('initiative_id', sa.String(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voting_option_creator_id'), 'voting_option', ['creator_id'], unique=False)
    op.create_index(op.f('ix_voting_option_initiative_id'), 'voting_option', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_voting_option_rule_id'), 'voting_option', ['rule_id'], unique=False)
    op.create_table('voting_result',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vote', sa.Boolean(), nullable=True),
    sa.Column('is_significant_minority', sa.Boolean(), nullable=False),
    sa.Column('is_noncompliance_minority', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('minority_options', sa.JSON(), nullable=False),
    sa.Column('noncompliance', sa.JSON(), nullable=False),
    sa.Column('minority_noncompliance', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_user_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_data_user_id'), 'auth_user_data', ['user_id'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_community_id'), 'category', ['community_id'], unique=False)
    op.create_index(op.f('ix_category_creator_id'), 'category', ['creator_id'], unique=False)
    op.create_index(op.f('ix_category_status_id'), 'category', ['status_id'], unique=False)
    op.create_table('community_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_id', sa.String(), nullable=False),
    sa.Column('description_id', sa.String(), nullable=False),
    sa.Column('quorum', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.Column('significant_minority', sa.Integer(), nullable=False),
    sa.Column('decision_delay', sa.Integer(), nullable=False),
    sa.Column('dispute_time_limit', sa.Integer(), nullable=False),
    sa.Column('last_voting_params', sa.JSON(), nullable=True),
    sa.Column('is_secret_ballot', sa.Boolean(), nullable=False),
    sa.Column('is_can_offer', sa.Boolean(), nullable=False),
    sa.Column('is_minority_not_participate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['description_id'], ['community_description.id'], ),
    sa.ForeignKeyConstraint(['name_id'], ['community_name.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_settings_description_id'), 'community_settings', ['description_id'], unique=False)
    op.create_index(op.f('ix_community_settings_name_id'), 'community_settings', ['name_id'], unique=False)
    op.create_table('opinion',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('initiative_id', sa.String(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opinion_creator_id'), 'opinion', ['creator_id'], unique=False)
    op.create_index(op.f('ix_opinion_initiative_id'), 'opinion', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_opinion_rule_id'), 'opinion', ['rule_id'], unique=False)
    op.create_table('user_community_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('parent_community_id', sa.String(), nullable=True),
    sa.Column('quorum', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.Column('significant_minority', sa.Integer(), nullable=False),
    sa.Column('decision_delay', sa.Integer(), nullable=False),
    sa.Column('dispute_time_limit', sa.Integer(), nullable=False),
    sa.Column('is_secret_ballot', sa.Boolean(), nullable=False),
    sa.Column('is_can_offer', sa.Boolean(), nullable=False),
    sa.Column('is_minority_not_participate', sa.Boolean(), nullable=False),
    sa.Column('is_not_delegate', sa.Boolean(), nullable=False),
    sa.Column('is_default_add_member', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'community_id', name='idx_unique_user_cs_community_user')
    )
    op.create_index(op.f('ix_user_community_settings_community_id'), 'user_community_settings', ['community_id'], unique=False)
    op.create_index(op.f('ix_user_community_settings_parent_community_id'), 'user_community_settings', ['parent_community_id'], unique=False)
    op.create_index(op.f('ix_user_community_settings_quorum'), 'user_community_settings', ['quorum'], unique=False)
    op.create_index(op.f('ix_user_community_settings_significant_minority'), 'user_community_settings', ['significant_minority'], unique=False)
    op.create_index(op.f('ix_user_community_settings_user_id'), 'user_community_settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_community_settings_vote'), 'user_community_settings', ['vote'], unique=False)
    op.create_table('user_voting_result',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vote', sa.Boolean(), nullable=True),
    sa.Column('is_voted_myself', sa.Boolean(), nullable=False),
    sa.Column('is_voted_by_default', sa.Boolean(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('voting_result_id', sa.String(), nullable=False),
    sa.Column('initiative_id', sa.String(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['voting_result_id'], ['voting_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_voting_result_community_id'), 'user_voting_result', ['community_id'], unique=False)
    op.create_index(op.f('ix_user_voting_result_initiative_id'), 'user_voting_result', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_user_voting_result_member_id'), 'user_voting_result', ['member_id'], unique=False)
    op.create_index(op.f('ix_user_voting_result_rule_id'), 'user_voting_result', ['rule_id'], unique=False)
    op.create_index(op.f('ix_user_voting_result_voting_result_id'), 'user_voting_result', ['voting_result_id'], unique=False)
    op.create_table('challenge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('old_category_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['old_category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_category_id'), 'challenge', ['category_id'], unique=False)
    op.create_index(op.f('ix_challenge_community_id'), 'challenge', ['community_id'], unique=False)
    op.create_index(op.f('ix_challenge_creator_id'), 'challenge', ['creator_id'], unique=False)
    op.create_index(op.f('ix_challenge_status_id'), 'challenge', ['status_id'], unique=False)
    op.create_table('community',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('main_settings_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('tracker', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['main_settings_id'], ['community_settings.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['community.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_creator_id'), 'community', ['creator_id'], unique=False)
    op.create_index(op.f('ix_community_main_settings_id'), 'community', ['main_settings_id'], unique=False)
    op.create_index(op.f('ix_community_parent_id'), 'community', ['parent_id'], unique=False)
    op.create_index(op.f('ix_community_tracker'), 'community', ['tracker'], unique=False)
    op.create_table('delegate_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('delegate_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['delegate_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegate_settings_category_id'), 'delegate_settings', ['category_id'], unique=False)
    op.create_index(op.f('ix_delegate_settings_community_id'), 'delegate_settings', ['community_id'], unique=False)
    op.create_index(op.f('ix_delegate_settings_delegate_id'), 'delegate_settings', ['delegate_id'], unique=False)
    op.create_index(op.f('ix_delegate_settings_user_id'), 'delegate_settings', ['user_id'], unique=False)
    op.create_table('initiative',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_one_day_event', sa.Boolean(), nullable=False),
    sa.Column('is_extra_options', sa.Boolean(), nullable=False),
    sa.Column('is_multi_select', sa.Boolean(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('old_category_id', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('voting_result_id', sa.String(), nullable=False),
    sa.Column('extra_question', sa.String(), nullable=True),
    sa.Column('responsible_id', sa.String(), nullable=True),
    sa.Column('tracker', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['old_category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['voting_result_id'], ['voting_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initiative_category_id'), 'initiative', ['category_id'], unique=False)
    op.create_index(op.f('ix_initiative_community_id'), 'initiative', ['community_id'], unique=False)
    op.create_index(op.f('ix_initiative_creator_id'), 'initiative', ['creator_id'], unique=False)
    op.create_index(op.f('ix_initiative_responsible_id'), 'initiative', ['responsible_id'], unique=False)
    op.create_index(op.f('ix_initiative_status_id'), 'initiative', ['status_id'], unique=False)
    op.create_index(op.f('ix_initiative_tracker'), 'initiative', ['tracker'], unique=False)
    op.create_index(op.f('ix_initiative_voting_result_id'), 'initiative', ['voting_result_id'], unique=False)
    op.create_table('relation_community_settings_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['community_settings.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_cs_category')
    )
    op.create_index(op.f('ix_relation_community_settings_categories_from_id'), 'relation_community_settings_categories', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_community_settings_categories_to_id'), 'relation_community_settings_categories', ['to_id'], unique=False)
    op.create_table('relation_community_settings_responsibilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['community_settings.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['responsibility.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_cs_responsibility')
    )
    op.create_index(op.f('ix_relation_community_settings_responsibilities_from_id'), 'relation_community_settings_responsibilities', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_community_settings_responsibilities_to_id'), 'relation_community_settings_responsibilities', ['to_id'], unique=False)
    op.create_table('relation_community_settings_user_cs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['community_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['user_community_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_community_settings_user_community_settings')
    )
    op.create_index(op.f('ix_relation_community_settings_user_cs_from_id'), 'relation_community_settings_user_cs', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_community_settings_user_cs_to_id'), 'relation_community_settings_user_cs', ['to_id'], unique=False)
    op.create_table('relation_ucs_descriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['community_description.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_cs_description')
    )
    op.create_index(op.f('ix_relation_ucs_descriptions_from_id'), 'relation_ucs_descriptions', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_ucs_descriptions_to_id'), 'relation_ucs_descriptions', ['to_id'], unique=False)
    op.create_table('relation_ucs_names',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['community_name.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_cs_name')
    )
    op.create_index(op.f('ix_relation_ucs_names_from_id'), 'relation_ucs_names', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_ucs_names_to_id'), 'relation_ucs_names', ['to_id'], unique=False)
    op.create_table('relation_user_community_settings_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_community_settings_categories')
    )
    op.create_index(op.f('ix_relation_user_community_settings_categories_from_id'), 'relation_user_community_settings_categories', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_community_settings_categories_to_id'), 'relation_user_community_settings_categories', ['to_id'], unique=False)
    op.create_table('relation_user_community_settings_responsibilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['responsibility.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_cs_responsibility')
    )
    op.create_index(op.f('ix_relation_user_community_settings_responsibilities_from_id'), 'relation_user_community_settings_responsibilities', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_community_settings_responsibilities_to_id'), 'relation_user_community_settings_responsibilities', ['to_id'], unique=False)
    op.create_table('relation_user_community_settings_user_cs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['user_community_settings.id'], ),
    sa.PrimaryKeyConstraint('id', 'from_id', 'to_id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_community_settings_user_cs')
    )
    op.create_table('relation_user_voting_result_noncompliance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['user_voting_result.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['noncompliance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_voting_result_noncompliance')
    )
    op.create_index(op.f('ix_relation_user_voting_result_noncompliance_from_id'), 'relation_user_voting_result_noncompliance', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_voting_result_noncompliance_to_id'), 'relation_user_voting_result_noncompliance', ['to_id'], unique=False)
    op.create_table('relation_user_voting_result_voting_options',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['user_voting_result.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['voting_option.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_voting_result_voting_option')
    )
    op.create_index(op.f('ix_relation_user_voting_result_voting_options_from_id'), 'relation_user_voting_result_voting_options', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_voting_result_voting_options_to_id'), 'relation_user_voting_result_voting_options', ['to_id'], unique=False)
    op.create_table('rule',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_extra_options', sa.Boolean(), nullable=False),
    sa.Column('is_multi_select', sa.Boolean(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('old_category_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('voting_result_id', sa.String(), nullable=False),
    sa.Column('extra_question', sa.String(), nullable=True),
    sa.Column('tracker', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['old_category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['voting_result_id'], ['voting_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_category_id'), 'rule', ['category_id'], unique=False)
    op.create_index(op.f('ix_rule_community_id'), 'rule', ['community_id'], unique=False)
    op.create_index(op.f('ix_rule_creator_id'), 'rule', ['creator_id'], unique=False)
    op.create_index(op.f('ix_rule_status_id'), 'rule', ['status_id'], unique=False)
    op.create_index(op.f('ix_rule_tracker'), 'rule', ['tracker'], unique=False)
    op.create_index(op.f('ix_rule_voting_result_id'), 'rule', ['voting_result_id'], unique=False)
    op.create_table('relation_challenge_solutions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['challenge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['solution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_challenge_solutions')
    )
    op.create_index(op.f('ix_relation_challenge_solutions_from_id'), 'relation_challenge_solutions', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_challenge_solutions_to_id'), 'relation_challenge_solutions', ['to_id'], unique=False)
    op.create_table('relation_community_user_community_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['user_community_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_community_user_community_settings')
    )
    op.create_index(op.f('ix_relation_community_user_community_settings_from_id'), 'relation_community_user_community_settings', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_community_user_community_settings_to_id'), 'relation_community_user_community_settings', ['to_id'], unique=False)
    op.create_table('request_member',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('vote', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'community_id', 'parent_id', 'creator_id', name='idx_unique_request_member')
    )
    op.create_index(op.f('ix_request_member_community_id'), 'request_member', ['community_id'], unique=False)
    op.create_index(op.f('ix_request_member_creator_id'), 'request_member', ['creator_id'], unique=False)
    op.create_index(op.f('ix_request_member_member_id'), 'request_member', ['member_id'], unique=False)
    op.create_index(op.f('ix_request_member_status_id'), 'request_member', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_member_status_id'), table_name='request_member')
    op.drop_index(op.f('ix_request_member_member_id'), table_name='request_member')
    op.drop_index(op.f('ix_request_member_creator_id'), table_name='request_member')
    op.drop_index(op.f('ix_request_member_community_id'), table_name='request_member')
    op.drop_table('request_member')
    op.drop_index(op.f('ix_relation_community_user_community_settings_to_id'), table_name='relation_community_user_community_settings')
    op.drop_index(op.f('ix_relation_community_user_community_settings_from_id'), table_name='relation_community_user_community_settings')
    op.drop_table('relation_community_user_community_settings')
    op.drop_index(op.f('ix_relation_challenge_solutions_to_id'), table_name='relation_challenge_solutions')
    op.drop_index(op.f('ix_relation_challenge_solutions_from_id'), table_name='relation_challenge_solutions')
    op.drop_table('relation_challenge_solutions')
    op.drop_index(op.f('ix_rule_voting_result_id'), table_name='rule')
    op.drop_index(op.f('ix_rule_tracker'), table_name='rule')
    op.drop_index(op.f('ix_rule_status_id'), table_name='rule')
    op.drop_index(op.f('ix_rule_creator_id'), table_name='rule')
    op.drop_index(op.f('ix_rule_community_id'), table_name='rule')
    op.drop_index(op.f('ix_rule_category_id'), table_name='rule')
    op.drop_table('rule')
    op.drop_index(op.f('ix_relation_user_voting_result_voting_options_to_id'), table_name='relation_user_voting_result_voting_options')
    op.drop_index(op.f('ix_relation_user_voting_result_voting_options_from_id'), table_name='relation_user_voting_result_voting_options')
    op.drop_table('relation_user_voting_result_voting_options')
    op.drop_index(op.f('ix_relation_user_voting_result_noncompliance_to_id'), table_name='relation_user_voting_result_noncompliance')
    op.drop_index(op.f('ix_relation_user_voting_result_noncompliance_from_id'), table_name='relation_user_voting_result_noncompliance')
    op.drop_table('relation_user_voting_result_noncompliance')
    op.drop_table('relation_user_community_settings_user_cs')
    op.drop_index(op.f('ix_relation_user_community_settings_responsibilities_to_id'), table_name='relation_user_community_settings_responsibilities')
    op.drop_index(op.f('ix_relation_user_community_settings_responsibilities_from_id'), table_name='relation_user_community_settings_responsibilities')
    op.drop_table('relation_user_community_settings_responsibilities')
    op.drop_index(op.f('ix_relation_user_community_settings_categories_to_id'), table_name='relation_user_community_settings_categories')
    op.drop_index(op.f('ix_relation_user_community_settings_categories_from_id'), table_name='relation_user_community_settings_categories')
    op.drop_table('relation_user_community_settings_categories')
    op.drop_index(op.f('ix_relation_ucs_names_to_id'), table_name='relation_ucs_names')
    op.drop_index(op.f('ix_relation_ucs_names_from_id'), table_name='relation_ucs_names')
    op.drop_table('relation_ucs_names')
    op.drop_index(op.f('ix_relation_ucs_descriptions_to_id'), table_name='relation_ucs_descriptions')
    op.drop_index(op.f('ix_relation_ucs_descriptions_from_id'), table_name='relation_ucs_descriptions')
    op.drop_table('relation_ucs_descriptions')
    op.drop_index(op.f('ix_relation_community_settings_user_cs_to_id'), table_name='relation_community_settings_user_cs')
    op.drop_index(op.f('ix_relation_community_settings_user_cs_from_id'), table_name='relation_community_settings_user_cs')
    op.drop_table('relation_community_settings_user_cs')
    op.drop_index(op.f('ix_relation_community_settings_responsibilities_to_id'), table_name='relation_community_settings_responsibilities')
    op.drop_index(op.f('ix_relation_community_settings_responsibilities_from_id'), table_name='relation_community_settings_responsibilities')
    op.drop_table('relation_community_settings_responsibilities')
    op.drop_index(op.f('ix_relation_community_settings_categories_to_id'), table_name='relation_community_settings_categories')
    op.drop_index(op.f('ix_relation_community_settings_categories_from_id'), table_name='relation_community_settings_categories')
    op.drop_table('relation_community_settings_categories')
    op.drop_index(op.f('ix_initiative_voting_result_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_tracker'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_status_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_responsible_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_creator_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_community_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_category_id'), table_name='initiative')
    op.drop_table('initiative')
    op.drop_index(op.f('ix_delegate_settings_user_id'), table_name='delegate_settings')
    op.drop_index(op.f('ix_delegate_settings_delegate_id'), table_name='delegate_settings')
    op.drop_index(op.f('ix_delegate_settings_community_id'), table_name='delegate_settings')
    op.drop_index(op.f('ix_delegate_settings_category_id'), table_name='delegate_settings')
    op.drop_table('delegate_settings')
    op.drop_index(op.f('ix_community_tracker'), table_name='community')
    op.drop_index(op.f('ix_community_parent_id'), table_name='community')
    op.drop_index(op.f('ix_community_main_settings_id'), table_name='community')
    op.drop_index(op.f('ix_community_creator_id'), table_name='community')
    op.drop_table('community')
    op.drop_index(op.f('ix_challenge_status_id'), table_name='challenge')
    op.drop_index(op.f('ix_challenge_creator_id'), table_name='challenge')
    op.drop_index(op.f('ix_challenge_community_id'), table_name='challenge')
    op.drop_index(op.f('ix_challenge_category_id'), table_name='challenge')
    op.drop_table('challenge')
    op.drop_index(op.f('ix_user_voting_result_voting_result_id'), table_name='user_voting_result')
    op.drop_index(op.f('ix_user_voting_result_rule_id'), table_name='user_voting_result')
    op.drop_index(op.f('ix_user_voting_result_member_id'), table_name='user_voting_result')
    op.drop_index(op.f('ix_user_voting_result_initiative_id'), table_name='user_voting_result')
    op.drop_index(op.f('ix_user_voting_result_community_id'), table_name='user_voting_result')
    op.drop_table('user_voting_result')
    op.drop_index(op.f('ix_user_community_settings_vote'), table_name='user_community_settings')
    op.drop_index(op.f('ix_user_community_settings_user_id'), table_name='user_community_settings')
    op.drop_index(op.f('ix_user_community_settings_significant_minority'), table_name='user_community_settings')
    op.drop_index(op.f('ix_user_community_settings_quorum'), table_name='user_community_settings')
    op.drop_index(op.f('ix_user_community_settings_parent_community_id'), table_name='user_community_settings')
    op.drop_index(op.f('ix_user_community_settings_community_id'), table_name='user_community_settings')
    op.drop_table('user_community_settings')
    op.drop_index(op.f('ix_opinion_rule_id'), table_name='opinion')
    op.drop_index(op.f('ix_opinion_initiative_id'), table_name='opinion')
    op.drop_index(op.f('ix_opinion_creator_id'), table_name='opinion')
    op.drop_table('opinion')
    op.drop_index(op.f('ix_community_settings_name_id'), table_name='community_settings')
    op.drop_index(op.f('ix_community_settings_description_id'), table_name='community_settings')
    op.drop_table('community_settings')
    op.drop_index(op.f('ix_category_status_id'), table_name='category')
    op.drop_index(op.f('ix_category_creator_id'), table_name='category')
    op.drop_index(op.f('ix_category_community_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_auth_user_data_user_id'), table_name='auth_user_data')
    op.drop_table('auth_user_data')
    op.drop_table('voting_result')
    op.drop_index(op.f('ix_voting_option_rule_id'), table_name='voting_option')
    op.drop_index(op.f('ix_voting_option_initiative_id'), table_name='voting_option')
    op.drop_index(op.f('ix_voting_option_creator_id'), table_name='voting_option')
    op.drop_table('voting_option')
    op.drop_table('status')
    op.drop_index(op.f('ix_solution_creator_id'), table_name='solution')
    op.drop_table('solution')
    op.drop_index(op.f('ix_responsibility_creator_id'), table_name='responsibility')
    op.drop_index(op.f('ix_responsibility_community_id'), table_name='responsibility')
    op.drop_table('responsibility')
    op.drop_index(op.f('ix_noncompliance_creator_id'), table_name='noncompliance')
    op.drop_index(op.f('ix_noncompliance_community_id'), table_name='noncompliance')
    op.drop_table('noncompliance')
    op.drop_table('file_metadata')
    op.drop_index(op.f('ix_community_name_creator_id'), table_name='community_name')
    op.drop_index(op.f('ix_community_name_community_id'), table_name='community_name')
    op.drop_table('community_name')
    op.drop_index(op.f('ix_community_description_value'), table_name='community_description')
    op.drop_index(op.f('ix_community_description_creator_id'), table_name='community_description')
    op.drop_table('community_description')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
