"""add opinion and like tables

Revision ID: 14e73cc3ac0b
Revises: d5755b584563
Create Date: 2024-04-06 15:47:00.878371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e73cc3ac0b'
down_revision: Union[str, None] = 'd5755b584563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opinion',
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('creator_id', sa.String(), nullable=False),
        sa.Column('initiative_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['initiative_id'], ['initiative.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opinion_creator_id'), 'opinion', ['creator_id'], unique=False)
    op.create_index(op.f('ix_opinion_initiative_id'), 'opinion', ['initiative_id'], unique=False)
    op.create_table('like',
        sa.Column('is_like', sa.Boolean(), nullable=False),
        sa.Column('creator_id', sa.String(), nullable=False),
        sa.Column('initiative_id', sa.String(), nullable=False),
        sa.Column('opinion_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['initiative_id'], ['initiative.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['opinion_id'], ['opinion.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_like_creator_id'), 'like', ['creator_id'], unique=False)
    op.create_index(op.f('ix_like_initiative_id'), 'like', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_like_opinion_id'), 'like', ['opinion_id'], unique=False)
    op.create_table('relation_initiative_opinion',
        sa.Column('initiative_id', sa.String(), nullable=False),
        sa.Column('opinion_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['initiative_id'], ['initiative.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['opinion_id'], ['opinion.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('initiative_id', 'opinion_id', name='idx_unique_initiative_opinion')
    )
    op.create_index(op.f('ix_relation_initiative_opinion_initiative_id'), 'relation_initiative_opinion', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_relation_initiative_opinion_opinion_id'), 'relation_initiative_opinion', ['opinion_id'], unique=False)
    op.create_table('relation_initiative_like',
        sa.Column('initiative_id', sa.String(), nullable=False),
        sa.Column('like_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['initiative_id'], ['initiative.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['like_id'], ['like.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('initiative_id', 'like_id', name='idx_unique_initiative_like')
    )
    op.create_index(op.f('ix_relation_initiative_like_initiative_id'), 'relation_initiative_like', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_relation_initiative_like_like_id'), 'relation_initiative_like', ['like_id'], unique=False)
    op.create_table('relation_opinion_like',
        sa.Column('opinion_id', sa.String(), nullable=False),
        sa.Column('like_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['like_id'], ['like.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['opinion_id'], ['opinion.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('opinion_id', 'like_id', name='idx_unique_opinion_like')
    )
    op.create_index(op.f('ix_relation_opinion_like_like_id'), 'relation_opinion_like', ['like_id'], unique=False)
    op.create_index(op.f('ix_relation_opinion_like_opinion_id'), 'relation_opinion_like', ['opinion_id'], unique=False)
    op.add_column('result_voting', sa.Column('initiative_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_result_voting_initiative_id'), 'result_voting', ['initiative_id'], unique=False)
    op.create_foreign_key(None, 'result_voting', 'initiative', ['initiative_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result_voting', type_='foreignkey')
    op.drop_index(op.f('ix_result_voting_initiative_id'), table_name='result_voting')
    op.drop_column('result_voting', 'initiative_id')
    op.drop_index(op.f('ix_relation_opinion_like_opinion_id'), table_name='relation_opinion_like')
    op.drop_index(op.f('ix_relation_opinion_like_like_id'), table_name='relation_opinion_like')
    op.drop_table('relation_opinion_like')
    op.drop_index(op.f('ix_relation_initiative_like_like_id'), table_name='relation_initiative_like')
    op.drop_index(op.f('ix_relation_initiative_like_initiative_id'), table_name='relation_initiative_like')
    op.drop_table('relation_initiative_like')
    op.drop_index(op.f('ix_relation_initiative_opinion_opinion_id'), table_name='relation_initiative_opinion')
    op.drop_index(op.f('ix_relation_initiative_opinion_initiative_id'), table_name='relation_initiative_opinion')
    op.drop_table('relation_initiative_opinion')
    op.drop_index(op.f('ix_like_opinion_id'), table_name='like')
    op.drop_index(op.f('ix_like_initiative_id'), table_name='like')
    op.drop_index(op.f('ix_like_creator_id'), table_name='like')
    op.drop_table('like')
    op.drop_index(op.f('ix_opinion_initiative_id'), table_name='opinion')
    op.drop_index(op.f('ix_opinion_creator_id'), table_name='opinion')
    op.drop_table('opinion')
    # ### end Alembic commands ###
