"""fix user table

Revision ID: 2360ca14ca93
Revises: c7f25883767a
Create Date: 2025-02-24 00:03:23.948762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2360ca14ca93'
down_revision: Union[str, None] = 'c7f25883767a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('fullname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'fullname')
    # ### end Alembic commands ###
