"""init tables

Revision ID: 2a3bd8705d7e
Revises: 
Create Date: 2024-03-19 22:14:42.944280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3bd8705d7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('firstname', sa.String(), nullable=False),
        sa.Column('surname', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_table('community',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('creator', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_creator'), 'community', ['creator'], unique=False)
    op.create_table('initiative_category',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('creator', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
        sa.ForeignKeyConstraint(['status'], ['status.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initiative_category_creator'), 'initiative_category', ['creator'], unique=False)
    op.create_index(op.f('ix_initiative_category_status'), 'initiative_category', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_initiative_category_status'), table_name='initiative_category')
    op.drop_index(op.f('ix_initiative_category_creator'), table_name='initiative_category')
    op.drop_table('initiative_category')
    op.drop_index(op.f('ix_community_creator'), table_name='community')
    op.drop_table('community')
    op.drop_table('user')
    op.drop_table('status')
    # ### end Alembic commands ###
