"""fix community_settings table

Revision ID: 30d41674911c
Revises: 3d0bee216f1b
Create Date: 2025-03-28 23:03:38.582319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d41674911c'
down_revision: Union[str, None] = '3d0bee216f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_settings', sa.Column('last_voting_params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_settings', 'last_voting_params')
    # ### end Alembic commands ###
