"""update user community settings table

Revision ID: 3ca946dc4556
Revises: 0b69f9d88d87
Create Date: 2024-05-01 20:24:42.698562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca946dc4556'
down_revision: Union[str, None] = '0b69f9d88d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_community_settings', sa.Column('is_default_add_member', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_community_settings', 'is_default_add_member')
    # ### end Alembic commands ###
