"""fix some lab tables

Revision ID: 457680438cd5
Revises: 6f81b2d5ad6c
Create Date: 2025-09-29 23:24:03.167318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457680438cd5'
down_revision: Union[str, None] = '6f81b2d5ad6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combination_source_element', sa.Column('combination_id', sa.String(), nullable=False))
    op.drop_index('ix_combination_source_element_interaction_combination_id', table_name='combination_source_element')
    op.drop_index('idx_combination_source', table_name='combination_source_element')
    op.create_index('idx_combination_source', 'combination_source_element', ['combination_id', 'source_solution_id'], unique=False)
    op.create_index(op.f('ix_combination_source_element_combination_id'), 'combination_source_element', ['combination_id'], unique=False)
    op.drop_constraint('combination_source_element_interaction_combination_id_fkey', 'combination_source_element', type_='foreignkey')
    op.create_foreign_key(None, 'combination_source_element', 'interaction_combination', ['combination_id'], ['id'])
    op.drop_column('combination_source_element', 'interaction_combination_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combination_source_element', sa.Column('interaction_combination_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'combination_source_element', type_='foreignkey')
    op.create_foreign_key('combination_source_element_interaction_combination_id_fkey', 'combination_source_element', 'interaction_combination', ['interaction_combination_id'], ['id'])
    op.drop_index(op.f('ix_combination_source_element_combination_id'), table_name='combination_source_element')
    op.drop_index('idx_combination_source', table_name='combination_source_element')
    op.create_index('idx_combination_source', 'combination_source_element', ['interaction_combination_id', 'source_solution_id'], unique=False)
    op.create_index('ix_combination_source_element_interaction_combination_id', 'combination_source_element', ['interaction_combination_id'], unique=False)
    op.drop_column('combination_source_element', 'combination_id')
    # ### end Alembic commands ###
