"""fix opinion table

Revision ID: 462900b4691c
Revises: 2360ca14ca93
Create Date: 2025-02-24 22:59:06.809936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462900b4691c'
down_revision: Union[str, None] = '2360ca14ca93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opinion', sa.Column('initiative_id', sa.String(), nullable=True))
    op.add_column('opinion', sa.Column('rule_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_opinion_initiative_id'), 'opinion', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_opinion_rule_id'), 'opinion', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opinion_rule_id'), table_name='opinion')
    op.drop_index(op.f('ix_opinion_initiative_id'), table_name='opinion')
    op.drop_column('opinion', 'rule_id')
    op.drop_column('opinion', 'initiative_id')
    # ### end Alembic commands ###
