"""Fix UserCommunitySettings table

Revision ID: 475977a678c3
Revises: 47ce006b363d
Create Date: 2024-08-31 18:04:32.690541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475977a678c3'
down_revision: Union[str, None] = '47ce006b363d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('relation_community_user_community_settings_from_id_fkey', 'relation_community_user_community_settings', type_='foreignkey')
    op.drop_constraint('relation_community_user_community_settings_to_id_fkey', 'relation_community_user_community_settings', type_='foreignkey')
    op.create_foreign_key(None, 'relation_community_user_community_settings', 'user_community_settings', ['to_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relation_community_user_community_settings', 'community', ['from_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relation_community_user_community_settings', type_='foreignkey')
    op.drop_constraint(None, 'relation_community_user_community_settings', type_='foreignkey')
    op.create_foreign_key('relation_community_user_community_settings_to_id_fkey', 'relation_community_user_community_settings', 'user_community_settings', ['to_id'], ['id'])
    op.create_foreign_key('relation_community_user_community_settings_from_id_fkey', 'relation_community_user_community_settings', 'community', ['from_id'], ['id'])
    # ### end Alembic commands ###
