"""add initiative table

Revision ID: 4ba405b15c55
Revises: 6e87df010c18
Create Date: 2024-03-20 23:30:54.712317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba405b15c55'
down_revision: Union[str, None] = '6e87df010c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initiative',
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('creator', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['category'], ['initiative_category.id'], ),
        sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
        sa.ForeignKeyConstraint(['status'], ['status.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initiative_category'), 'initiative', ['category'], unique=False)
    op.create_index(op.f('ix_initiative_creator'), 'initiative', ['creator'], unique=False)
    op.create_index(op.f('ix_initiative_status'), 'initiative', ['status'], unique=False)
    op.alter_column('relation_cs_categories', 'cs_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('relation_cs_categories', 'init_category_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relation_cs_categories', 'init_category_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('relation_cs_categories', 'cs_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_initiative_status'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_creator'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_category'), table_name='initiative')
    op.drop_table('initiative')
    # ### end Alembic commands ###
