"""fix request member table

Revision ID: 533c9ca48bbb
Revises: 30d41674911c
Create Date: 2025-03-29 09:21:23.628522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533c9ca48bbb'
down_revision: Union[str, None] = '30d41674911c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_member', 'is_blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_member', sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
