"""Add ondelete=CASCADE for request member

Revision ID: 55b182fdc84f
Revises: e6e881f56851
Create Date: 2024-08-25 23:02:00.941918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b182fdc84f'
down_revision: Union[str, None] = 'e6e881f56851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('relation_cs_request_member_to_id_fkey', 'relation_cs_request_member', type_='foreignkey')
    op.drop_constraint('relation_cs_request_member_from_id_fkey', 'relation_cs_request_member', type_='foreignkey')
    op.create_foreign_key(None, 'relation_cs_request_member', 'community_settings', ['from_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relation_cs_request_member', 'request_member', ['to_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('relation_user_cs_request_member_from_id_fkey', 'relation_user_cs_request_member', type_='foreignkey')
    op.drop_constraint('relation_user_cs_request_member_to_id_fkey', 'relation_user_cs_request_member', type_='foreignkey')
    op.create_foreign_key(None, 'relation_user_cs_request_member', 'user_community_settings', ['from_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relation_user_cs_request_member', 'request_member', ['to_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relation_user_cs_request_member', type_='foreignkey')
    op.drop_constraint(None, 'relation_user_cs_request_member', type_='foreignkey')
    op.create_foreign_key('relation_user_cs_request_member_to_id_fkey', 'relation_user_cs_request_member', 'request_member', ['to_id'], ['id'])
    op.create_foreign_key('relation_user_cs_request_member_from_id_fkey', 'relation_user_cs_request_member', 'user_community_settings', ['from_id'], ['id'])
    op.drop_constraint(None, 'relation_cs_request_member', type_='foreignkey')
    op.drop_constraint(None, 'relation_cs_request_member', type_='foreignkey')
    op.create_foreign_key('relation_cs_request_member_from_id_fkey', 'relation_cs_request_member', 'community_settings', ['from_id'], ['id'])
    op.create_foreign_key('relation_cs_request_member_to_id_fkey', 'relation_cs_request_member', 'request_member', ['to_id'], ['id'])
    # ### end Alembic commands ###
