"""fix solution table

Revision ID: 5660c8eb72b3
Revises: 457680438cd5
Create Date: 2025-10-01 19:33:52.772871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5660c8eb72b3'
down_revision: Union[str, None] = '457680438cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'solution', 'auth_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solution', type_='foreignkey')
    # ### end Alembic commands ###
