"""fix request_member table

Revision ID: 5b92ee695b57
Revises: b70e9e0fcfb6
Create Date: 2024-08-04 09:00:09.140455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b92ee695b57'
down_revision: Union[str, None] = 'b70e9e0fcfb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_request_member_community', 'request_member', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_unique_request_member_community', 'request_member', ['member_id', 'community_id'])
    # ### end Alembic commands ###
