"""Fix RequestMember model

Revision ID: 66a5fcdbef70
Revises: bf87a6b08448
Create Date: 2024-08-11 12:28:17.918414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a5fcdbef70'
down_revision: Union[str, None] = 'bf87a6b08448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_member_creator_id', table_name='request_member')
    op.drop_constraint('request_member_creator_id_fkey', 'request_member', type_='foreignkey')
    op.drop_column('request_member', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_member', sa.Column('creator_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('request_member_creator_id_fkey', 'request_member', 'user', ['creator_id'], ['id'])
    op.create_index('ix_request_member_creator_id', 'request_member', ['creator_id'], unique=False)
    # ### end Alembic commands ###
