"""add relation_cs_categories table

Revision ID: 6e87df010c18
Revises: ca0c6c32a559
Create Date: 2024-03-19 22:21:11.409312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e87df010c18'
down_revision: Union[str, None] = 'ca0c6c32a559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_cs_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cs_id', sa.String(), nullable=True),
    sa.Column('init_category_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cs_id'], ['community_settings.id'], ),
    sa.ForeignKeyConstraint(['init_category_id'], ['initiative_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cs_id', 'init_category_id', name='idx_unique_cs_init_category')
    )
    op.create_index(op.f('ix_relation_cs_categories_cs_id'), 'relation_cs_categories', ['cs_id'], unique=False)
    op.create_index(op.f('ix_relation_cs_categories_init_category_id'), 'relation_cs_categories', ['init_category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relation_cs_categories_init_category_id'), table_name='relation_cs_categories')
    op.drop_index(op.f('ix_relation_cs_categories_cs_id'), table_name='relation_cs_categories')
    op.drop_table('relation_cs_categories')
    # ### end Alembic commands ###
