"""add lab tables

Revision ID: 6f81b2d5ad6c
Revises: 5ffa3979baf7
Create Date: 2025-09-24 10:05:55.814701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f81b2d5ad6c'
down_revision: Union[str, None] = '5ffa3979baf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collective_interaction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('solution_id', sa.String(), nullable=False),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('user_response', sa.String(), nullable=False),
    sa.Column('user_reasoning', sa.String(), nullable=True),
    sa.Column('applied_to_solution', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interaction_solution_created', 'collective_interaction', ['solution_id', 'created_at'], unique=False)
    op.create_index('idx_interaction_type_response', 'collective_interaction', ['interaction_type', 'user_response'], unique=False)
    op.create_index(op.f('ix_collective_interaction_solution_id'), 'collective_interaction', ['solution_id'], unique=False)
    op.create_table('solution_version',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('solution_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('change_description', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solution_id', 'version_number', name='uq_solution_version_number')
    )
    op.create_index('idx_version_solution_number', 'solution_version', ['solution_id', 'version_number'], unique=False)
    op.create_index(op.f('ix_solution_version_solution_id'), 'solution_version', ['solution_id'], unique=False)
    op.create_table('interaction_combination',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interaction_id', sa.String(), nullable=False),
    sa.Column('new_idea_description', sa.String(), nullable=False),
    sa.Column('potential_impact', sa.String(), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['collective_interaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_combination_interaction_id'), 'interaction_combination', ['interaction_id'], unique=False)
    op.create_table('interaction_criticism',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interaction_id', sa.String(), nullable=False),
    sa.Column('criticism_text', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('suggested_fix', sa.String(), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['collective_interaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_criticism_interaction_id'), 'interaction_criticism', ['interaction_id'], unique=False)
    op.create_table('interaction_suggestion',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interaction_id', sa.String(), nullable=False),
    sa.Column('element_description', sa.String(), nullable=False),
    sa.Column('integration_advice', sa.String(), nullable=False),
    sa.Column('source_solutions_count', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['collective_interaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_suggestion_interaction_id'), 'interaction_suggestion', ['interaction_id'], unique=False)
    op.create_table('version_interaction_influence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('solution_version_id', sa.String(), nullable=False),
    sa.Column('collective_interaction_id', sa.String(), nullable=False),
    sa.Column('influence_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['collective_interaction_id'], ['collective_interaction.id'], ),
    sa.ForeignKeyConstraint(['solution_version_id'], ['solution_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solution_version_id', 'collective_interaction_id', name='uq_version_interaction_influence')
    )
    op.create_index(op.f('ix_version_interaction_influence_collective_interaction_id'), 'version_interaction_influence', ['collective_interaction_id'], unique=False)
    op.create_index(op.f('ix_version_interaction_influence_solution_version_id'), 'version_interaction_influence', ['solution_version_id'], unique=False)
    op.create_table('combination_source_element',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interaction_combination_id', sa.String(), nullable=False),
    sa.Column('source_solution_id', sa.String(), nullable=False),
    sa.Column('element_description', sa.String(), nullable=False),
    sa.Column('element_context', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_combination_id'], ['interaction_combination.id'], ),
    sa.ForeignKeyConstraint(['source_solution_id'], ['solution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_combination_source', 'combination_source_element', ['interaction_combination_id', 'source_solution_id'], unique=False)
    op.create_index(op.f('ix_combination_source_element_interaction_combination_id'), 'combination_source_element', ['interaction_combination_id'], unique=False)
    op.create_index(op.f('ix_combination_source_element_source_solution_id'), 'combination_source_element', ['source_solution_id'], unique=False)
    op.drop_index('ix_relation_challenge_solutions_from_id', table_name='relation_challenge_solutions')
    op.drop_index('ix_relation_challenge_solutions_to_id', table_name='relation_challenge_solutions')
    op.drop_table('relation_challenge_solutions')
    op.add_column('challenge', sa.Column('title', sa.String(), nullable=False))
    op.add_column('challenge', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('challenge', 'content')
    op.drop_column('challenge', 'question')
    op.add_column('solution', sa.Column('challenge_id', sa.String(), nullable=False))
    op.add_column('solution', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('solution', sa.Column('current_content', sa.String(), nullable=False))
    op.add_column('solution', sa.Column('status', sa.String(), nullable=False))
    op.add_column('solution', sa.Column('collective_influence_count', sa.Integer(), nullable=False))
    op.add_column('solution', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('solution', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_index('ix_solution_creator_id', table_name='solution')
    op.create_index('idx_solution_task_user', 'solution', ['challenge_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_solution_challenge_id'), 'solution', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_solution_user_id'), 'solution', ['user_id'], unique=False)
    op.create_unique_constraint('uq_task_user_solution', 'solution', ['challenge_id', 'user_id'])
    op.create_foreign_key(None, 'solution', 'challenge', ['challenge_id'], ['id'])
    op.drop_column('solution', 'text')
    op.drop_column('solution', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('creator_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('solution', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'solution', type_='foreignkey')
    op.drop_constraint('uq_task_user_solution', 'solution', type_='unique')
    op.drop_index(op.f('ix_solution_user_id'), table_name='solution')
    op.drop_index(op.f('ix_solution_challenge_id'), table_name='solution')
    op.drop_index('idx_solution_task_user', table_name='solution')
    op.create_index('ix_solution_creator_id', 'solution', ['creator_id'], unique=False)
    op.drop_column('solution', 'updated_at')
    op.drop_column('solution', 'created_at')
    op.drop_column('solution', 'collective_influence_count')
    op.drop_column('solution', 'status')
    op.drop_column('solution', 'current_content')
    op.drop_column('solution', 'user_id')
    op.drop_column('solution', 'challenge_id')
    op.add_column('challenge', sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('challenge', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('challenge', 'description')
    op.drop_column('challenge', 'title')
    op.create_table('relation_challenge_solutions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('from_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('to_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['challenge.id'], name='relation_challenge_solutions_from_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['solution.id'], name='relation_challenge_solutions_to_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='relation_challenge_solutions_pkey'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_challenge_solutions')
    )
    op.create_index('ix_relation_challenge_solutions_to_id', 'relation_challenge_solutions', ['to_id'], unique=False)
    op.create_index('ix_relation_challenge_solutions_from_id', 'relation_challenge_solutions', ['from_id'], unique=False)
    op.drop_index(op.f('ix_combination_source_element_source_solution_id'), table_name='combination_source_element')
    op.drop_index(op.f('ix_combination_source_element_interaction_combination_id'), table_name='combination_source_element')
    op.drop_index('idx_combination_source', table_name='combination_source_element')
    op.drop_table('combination_source_element')
    op.drop_index(op.f('ix_version_interaction_influence_solution_version_id'), table_name='version_interaction_influence')
    op.drop_index(op.f('ix_version_interaction_influence_collective_interaction_id'), table_name='version_interaction_influence')
    op.drop_table('version_interaction_influence')
    op.drop_index(op.f('ix_interaction_suggestion_interaction_id'), table_name='interaction_suggestion')
    op.drop_table('interaction_suggestion')
    op.drop_index(op.f('ix_interaction_criticism_interaction_id'), table_name='interaction_criticism')
    op.drop_table('interaction_criticism')
    op.drop_index(op.f('ix_interaction_combination_interaction_id'), table_name='interaction_combination')
    op.drop_table('interaction_combination')
    op.drop_index(op.f('ix_solution_version_solution_id'), table_name='solution_version')
    op.drop_index('idx_version_solution_number', table_name='solution_version')
    op.drop_table('solution_version')
    op.drop_index(op.f('ix_collective_interaction_solution_id'), table_name='collective_interaction')
    op.drop_index('idx_interaction_type_response', table_name='collective_interaction')
    op.drop_index('idx_interaction_solution_created', table_name='collective_interaction')
    op.drop_table('collective_interaction')
    # ### end Alembic commands ###
