"""fix relation fields

Revision ID: 7747158e7f42
Revises: 4ba405b15c55
Create Date: 2024-03-25 08:46:20.345737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7747158e7f42'
down_revision: Union[str, None] = '4ba405b15c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('main_settings_id', sa.String(), nullable=False))
    op.add_column('community', sa.Column('creator_id', sa.String(), nullable=False))
    op.drop_index('ix_community_creator', table_name='community')
    op.drop_index('ix_community_main_settings', table_name='community')
    op.create_index(op.f('ix_community_creator_id'), 'community', ['creator_id'], unique=False)
    op.create_index(op.f('ix_community_main_settings_id'), 'community', ['main_settings_id'], unique=False)
    op.drop_constraint('community_main_settings_fkey', 'community', type_='foreignkey')
    op.drop_constraint('community_creator_fkey', 'community', type_='foreignkey')
    op.create_foreign_key(None, 'community', 'user', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'community', 'community_settings', ['main_settings_id'], ['id'])
    op.drop_column('community', 'creator')
    op.drop_column('community', 'main_settings')
    op.add_column('community_settings', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('community_settings', sa.Column('community_id', sa.String(), nullable=True))
    op.drop_index('ix_community_settings_community', table_name='community_settings')
    op.drop_index('ix_community_settings_user', table_name='community_settings')
    op.create_index(op.f('ix_community_settings_community_id'), 'community_settings', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_settings_user_id'), 'community_settings', ['user_id'], unique=False)
    op.drop_constraint('community_settings_user_fkey', 'community_settings', type_='foreignkey')
    op.drop_constraint('community_settings_community_fkey', 'community_settings', type_='foreignkey')
    op.create_foreign_key(None, 'community_settings', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'community_settings', 'community', ['community_id'], ['id'])
    op.drop_column('community_settings', 'user')
    op.drop_column('community_settings', 'community')
    op.add_column('initiative', sa.Column('creator_id', sa.String(), nullable=False))
    op.add_column('initiative', sa.Column('status_id', sa.String(), nullable=False))
    op.add_column('initiative', sa.Column('category_id', sa.String(), nullable=False))
    op.drop_index('ix_initiative_category', table_name='initiative')
    op.drop_index('ix_initiative_creator', table_name='initiative')
    op.drop_index('ix_initiative_status', table_name='initiative')
    op.create_index(op.f('ix_initiative_category_id'), 'initiative', ['category_id'], unique=False)
    op.create_index(op.f('ix_initiative_creator_id'), 'initiative', ['creator_id'], unique=False)
    op.create_index(op.f('ix_initiative_status_id'), 'initiative', ['status_id'], unique=False)
    op.drop_constraint('initiative_creator_fkey', 'initiative', type_='foreignkey')
    op.drop_constraint('initiative_status_fkey', 'initiative', type_='foreignkey')
    op.drop_constraint('initiative_category_fkey', 'initiative', type_='foreignkey')
    op.create_foreign_key(None, 'initiative', 'user', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'initiative', 'initiative_category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'initiative', 'status', ['status_id'], ['id'])
    op.drop_column('initiative', 'category')
    op.drop_column('initiative', 'status')
    op.drop_column('initiative', 'creator')
    op.add_column('initiative_category', sa.Column('creator_id', sa.String(), nullable=False))
    op.add_column('initiative_category', sa.Column('status_id', sa.String(), nullable=False))
    op.drop_index('ix_initiative_category_creator', table_name='initiative_category')
    op.drop_index('ix_initiative_category_status', table_name='initiative_category')
    op.create_index(op.f('ix_initiative_category_creator_id'), 'initiative_category', ['creator_id'], unique=False)
    op.create_index(op.f('ix_initiative_category_status_id'), 'initiative_category', ['status_id'], unique=False)
    op.drop_constraint('initiative_category_status_fkey', 'initiative_category', type_='foreignkey')
    op.drop_constraint('initiative_category_creator_fkey', 'initiative_category', type_='foreignkey')
    op.create_foreign_key(None, 'initiative_category', 'status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'initiative_category', 'user', ['creator_id'], ['id'])
    op.drop_column('initiative_category', 'status')
    op.drop_column('initiative_category', 'creator')
    op.drop_constraint('relation_cs_categories_cs_id_fkey', 'relation_cs_categories', type_='foreignkey')
    op.drop_constraint('relation_cs_categories_init_category_id_fkey', 'relation_cs_categories', type_='foreignkey')
    op.create_foreign_key(None, 'relation_cs_categories', 'initiative_category', ['init_category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relation_cs_categories', 'community_settings', ['cs_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relation_cs_categories', type_='foreignkey')
    op.drop_constraint(None, 'relation_cs_categories', type_='foreignkey')
    op.create_foreign_key('relation_cs_categories_init_category_id_fkey', 'relation_cs_categories', 'initiative_category', ['init_category_id'], ['id'])
    op.create_foreign_key('relation_cs_categories_cs_id_fkey', 'relation_cs_categories', 'community_settings', ['cs_id'], ['id'])
    op.add_column('initiative_category', sa.Column('creator', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('initiative_category', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'initiative_category', type_='foreignkey')
    op.drop_constraint(None, 'initiative_category', type_='foreignkey')
    op.create_foreign_key('initiative_category_creator_fkey', 'initiative_category', 'user', ['creator'], ['id'])
    op.create_foreign_key('initiative_category_status_fkey', 'initiative_category', 'status', ['status'], ['id'])
    op.drop_index(op.f('ix_initiative_category_status_id'), table_name='initiative_category')
    op.drop_index(op.f('ix_initiative_category_creator_id'), table_name='initiative_category')
    op.create_index('ix_initiative_category_status', 'initiative_category', ['status'], unique=False)
    op.create_index('ix_initiative_category_creator', 'initiative_category', ['creator'], unique=False)
    op.drop_column('initiative_category', 'status_id')
    op.drop_column('initiative_category', 'creator_id')
    op.add_column('initiative', sa.Column('creator', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('initiative', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('initiative', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'initiative', type_='foreignkey')
    op.drop_constraint(None, 'initiative', type_='foreignkey')
    op.drop_constraint(None, 'initiative', type_='foreignkey')
    op.create_foreign_key('initiative_category_fkey', 'initiative', 'initiative_category', ['category'], ['id'])
    op.create_foreign_key('initiative_status_fkey', 'initiative', 'status', ['status'], ['id'])
    op.create_foreign_key('initiative_creator_fkey', 'initiative', 'user', ['creator'], ['id'])
    op.drop_index(op.f('ix_initiative_status_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_creator_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_category_id'), table_name='initiative')
    op.create_index('ix_initiative_status', 'initiative', ['status'], unique=False)
    op.create_index('ix_initiative_creator', 'initiative', ['creator'], unique=False)
    op.create_index('ix_initiative_category', 'initiative', ['category'], unique=False)
    op.drop_column('initiative', 'category_id')
    op.drop_column('initiative', 'status_id')
    op.drop_column('initiative', 'creator_id')
    op.add_column('community_settings', sa.Column('community', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('community_settings', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'community_settings', type_='foreignkey')
    op.drop_constraint(None, 'community_settings', type_='foreignkey')
    op.create_foreign_key('community_settings_community_fkey', 'community_settings', 'community', ['community'], ['id'])
    op.create_foreign_key('community_settings_user_fkey', 'community_settings', 'user', ['user'], ['id'])
    op.drop_index(op.f('ix_community_settings_user_id'), table_name='community_settings')
    op.drop_index(op.f('ix_community_settings_community_id'), table_name='community_settings')
    op.create_index('ix_community_settings_user', 'community_settings', ['user'], unique=False)
    op.create_index('ix_community_settings_community', 'community_settings', ['community'], unique=False)
    op.drop_column('community_settings', 'community_id')
    op.drop_column('community_settings', 'user_id')
    op.add_column('community', sa.Column('main_settings', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('community', sa.Column('creator', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'community', type_='foreignkey')
    op.drop_constraint(None, 'community', type_='foreignkey')
    op.create_foreign_key('community_creator_fkey', 'community', 'user', ['creator'], ['id'])
    op.create_foreign_key('community_main_settings_fkey', 'community', 'community_settings', ['main_settings'], ['id'])
    op.drop_index(op.f('ix_community_main_settings_id'), table_name='community')
    op.drop_index(op.f('ix_community_creator_id'), table_name='community')
    op.create_index('ix_community_main_settings', 'community', ['main_settings'], unique=False)
    op.create_index('ix_community_creator', 'community', ['creator'], unique=False)
    op.drop_column('community', 'creator_id')
    op.drop_column('community', 'main_settings_id')
    # ### end Alembic commands ###
