"""add indexes

Revision ID: 7f9f2035d0d0
Revises: fbdac374b3ec
Create Date: 2024-04-21 00:52:33.686702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9f2035d0d0'
down_revision: Union[str, None] = 'fbdac374b3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_community_description_user_id'), 'community_description', ['user_id'], unique=False)
    op.create_index(op.f('ix_community_description_value'), 'community_description', ['value'], unique=False)
    op.create_index(op.f('ix_community_name_community_id'), 'community_name', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_name_user_id'), 'community_name', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_name_user_id'), table_name='community_name')
    op.drop_index(op.f('ix_community_name_community_id'), table_name='community_name')
    op.drop_index(op.f('ix_community_description_value'), table_name='community_description')
    op.drop_index(op.f('ix_community_description_user_id'), table_name='community_description')
    # ### end Alembic commands ###
