"""fix_db_state

Revision ID: 8e726a00a4c7
Revises: 8f7dd0780f0b
Create Date: 2025-04-12 20:34:37.635017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e726a00a4c7'
down_revision: Union[str, None] = '8f7dd0780f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
