"""add relation table

Revision ID: 916b77233e98
Revises: d1ff9303c661
Create Date: 2024-04-15 12:39:34.546457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916b77233e98'
down_revision: Union[str, None] = 'd1ff9303c661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_user_community_settings_categories',
        sa.Column('from_id', sa.String(), nullable=False),
        sa.Column('to_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['to_id'], ['initiative_category.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_community_settings_init_categories')
    )
    op.create_index(op.f('ix_relation_user_community_settings_categories_from_id'), 'relation_user_community_settings_categories', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_community_settings_categories_to_id'), 'relation_user_community_settings_categories', ['to_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relation_user_community_settings_categories_to_id'), table_name='relation_user_community_settings_categories')
    op.drop_index(op.f('ix_relation_user_community_settings_categories_from_id'), table_name='relation_user_community_settings_categories')
    op.drop_table('relation_user_community_settings_categories')
    # ### end Alembic commands ###
