"""fix ucs table

Revision ID: 9d22ccd28363
Revises: 2dbcbc3aaf15
Create Date: 2024-04-15 22:19:51.469063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d22ccd28363'
down_revision: Union[str, None] = '2dbcbc3aaf15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_unique_user_cs_community_user', 'user_community_settings', ['user_id', 'community_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_user_cs_community_user', 'user_community_settings', type_='unique')
    # ### end Alembic commands ###
