"""fix tables

Revision ID: ab9f2ae153f8
Revises: 40a04d5b8d06
Create Date: 2025-03-19 21:14:16.504974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9f2ae153f8'
down_revision: Union[str, None] = '40a04d5b8d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relation_user_community_settings_delegate_settings_from_id', table_name='relation_user_community_settings_delegate_settings')
    op.drop_index('ix_relation_user_community_settings_delegate_settings_to_id', table_name='relation_user_community_settings_delegate_settings')
    op.drop_table('relation_user_community_settings_delegate_settings')
    op.drop_index('ix_relation_delegate_settings_users_from_id', table_name='relation_delegate_settings_users')
    op.drop_index('ix_relation_delegate_settings_users_to_id', table_name='relation_delegate_settings_users')
    op.drop_table('relation_delegate_settings_users')
    op.add_column('challenge', sa.Column('old_category_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'challenge', 'category', ['old_category_id'], ['id'])
    op.add_column('delegate_settings', sa.Column('community_id', sa.String(), nullable=False))
    op.add_column('delegate_settings', sa.Column('delegate_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_delegate_settings_community_id'), 'delegate_settings', ['community_id'], unique=False)
    op.create_index(op.f('ix_delegate_settings_delegate_id'), 'delegate_settings', ['delegate_id'], unique=False)
    op.create_foreign_key(None, 'delegate_settings', 'auth_user', ['delegate_id'], ['id'])
    op.add_column('initiative', sa.Column('old_category_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'initiative', 'category', ['old_category_id'], ['id'])
    op.add_column('rule', sa.Column('old_category_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'rule', 'category', ['old_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rule', type_='foreignkey')
    op.drop_column('rule', 'old_category_id')
    op.drop_constraint(None, 'initiative', type_='foreignkey')
    op.drop_column('initiative', 'old_category_id')
    op.drop_constraint(None, 'delegate_settings', type_='foreignkey')
    op.drop_index(op.f('ix_delegate_settings_delegate_id'), table_name='delegate_settings')
    op.drop_index(op.f('ix_delegate_settings_community_id'), table_name='delegate_settings')
    op.drop_column('delegate_settings', 'delegate_id')
    op.drop_column('delegate_settings', 'community_id')
    op.drop_constraint(None, 'challenge', type_='foreignkey')
    op.drop_column('challenge', 'old_category_id')
    op.create_table('relation_delegate_settings_users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('from_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('to_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['delegate_settings.id'], name='relation_delegate_settings_users_from_id_fkey'),
    sa.ForeignKeyConstraint(['to_id'], ['auth_user.id'], name='relation_delegate_settings_users_to_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='relation_delegate_settings_users_pkey'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_delegate_settings_users')
    )
    op.create_index('ix_relation_delegate_settings_users_to_id', 'relation_delegate_settings_users', ['to_id'], unique=False)
    op.create_index('ix_relation_delegate_settings_users_from_id', 'relation_delegate_settings_users', ['from_id'], unique=False)
    op.create_table('relation_user_community_settings_delegate_settings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('from_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('to_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], name='relation_user_community_settings_delegate_settings_from_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['delegate_settings.id'], name='relation_user_community_settings_delegate_settings_to_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='relation_user_community_settings_delegate_settings_pkey'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_community_settings_delegate_settings')
    )
    op.create_index('ix_relation_user_community_settings_delegate_settings_to_id', 'relation_user_community_settings_delegate_settings', ['to_id'], unique=False)
    op.create_index('ix_relation_user_community_settings_delegate_settings_from_id', 'relation_user_community_settings_delegate_settings', ['from_id'], unique=False)
    # ### end Alembic commands ###
