"""init commit

Revision ID: af4e64afd0d2
Revises: 
Create Date: 2024-09-14 00:00:39.887947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4e64afd0d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_description',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('value', sa.String(), nullable=False),
                    sa.Column('creator_id', sa.String(), nullable=False),
                    sa.Column('community_id', sa.String(), nullable=False),
                    sa.Column('is_readonly', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('value', 'community_id', name='idx_unique_community_description_id')
    )
    op.create_index(op.f('ix_community_description_creator_id'), 'community_description', ['creator_id'], unique=False)
    op.create_index(op.f('ix_community_description_value'), 'community_description', ['value'], unique=False)
    op.create_table('community_name',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('creator_id', sa.String(), nullable=False),
                    sa.Column('community_id', sa.String(), nullable=False),
                    sa.Column('is_readonly', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', 'community_id', name='idx_unique_community_name_id')
    )
    op.create_index(op.f('ix_community_name_community_id'), 'community_name', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_name_creator_id'), 'community_name', ['creator_id'], unique=False)
    op.create_table('file_metadata',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.Column('mimetype', sa.String(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initiative_type',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('code', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('is_like', sa.Boolean(), nullable=False),
                    sa.Column('creator_id', sa.String(), nullable=False),
                    sa.Column('initiative_id', sa.String(), nullable=True),
                    sa.Column('opinion_id', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_like_creator_id'), 'like', ['creator_id'], unique=False)
    op.create_index(op.f('ix_like_initiative_id'), 'like', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_like_opinion_id'), 'like', ['opinion_id'], unique=False)
    op.create_table('status',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('code', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('firstname', sa.String(), nullable=False),
                    sa.Column('surname', sa.String(), nullable=False),
                    sa.Column('about_me', sa.String(), nullable=True),
                    sa.Column('foto_id', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
    )
    op.create_table('voting_option',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('creator_id', sa.String(), nullable=False),
                    sa.Column('initiative_id', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voting_option_creator_id'), 'voting_option', ['creator_id'], unique=False)
    op.create_index(op.f('ix_voting_option_initiative_id'), 'voting_option', ['initiative_id'], unique=False)
    op.create_table('community_settings',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name_id', sa.String(), nullable=True),
                    sa.Column('description_id', sa.String(), nullable=True),
                    sa.Column('quorum', sa.Integer(), nullable=True),
                    sa.Column('vote', sa.Integer(), nullable=True),
                    sa.Column('is_secret_ballot', sa.Boolean(), nullable=False),
                    sa.Column('is_can_offer', sa.Boolean(), nullable=False),
                    sa.Column('is_minority_not_participate', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['description_id'], ['community_description.id'], ),
                    sa.ForeignKeyConstraint(['name_id'], ['community_name.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_settings_description_id'), 'community_settings', ['description_id'], unique=False)
    op.create_index(op.f('ix_community_settings_name_id'), 'community_settings', ['name_id'], unique=False)
    op.create_table('initiative_category',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('community_id', sa.String(), nullable=False),
                    sa.Column('creator_id', sa.String(), nullable=False),
                    sa.Column('status_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initiative_category_community_id'), 'initiative_category', ['community_id'], unique=False)
    op.create_index(op.f('ix_initiative_category_creator_id'), 'initiative_category', ['creator_id'], unique=False)
    op.create_index(op.f('ix_initiative_category_status_id'), 'initiative_category', ['status_id'], unique=False)
    op.create_table('opinion',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('creator_id', sa.String(), nullable=False),
                    sa.Column('initiative_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opinion_creator_id'), 'opinion', ['creator_id'], unique=False)
    op.create_index(op.f('ix_opinion_initiative_id'), 'opinion', ['initiative_id'], unique=False)
    op.create_table('user_community_settings',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('user_id', sa.String(), nullable=True),
                    sa.Column('community_id', sa.String(), nullable=False),
                    sa.Column('name_id', sa.String(), nullable=False),
                    sa.Column('description_id', sa.String(), nullable=False),
                    sa.Column('quorum', sa.Integer(), nullable=False),
                    sa.Column('vote', sa.Integer(), nullable=False),
                    sa.Column('is_secret_ballot', sa.Boolean(), nullable=False),
                    sa.Column('is_can_offer', sa.Boolean(), nullable=False),
                    sa.Column('is_minority_not_participate', sa.Boolean(), nullable=False),
                    sa.Column('is_not_delegate', sa.Boolean(), nullable=False),
                    sa.Column('is_default_add_member', sa.Boolean(), nullable=False),
                    sa.Column('is_blocked', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['description_id'], ['community_description.id'], ),
                    sa.ForeignKeyConstraint(['name_id'], ['community_name.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'community_id', name='idx_unique_user_cs_community_user')
    )
    op.create_index(op.f('ix_user_community_settings_community_id'), 'user_community_settings', ['community_id'], unique=False)
    op.create_index(op.f('ix_user_community_settings_description_id'), 'user_community_settings', ['description_id'], unique=False)
    op.create_index(op.f('ix_user_community_settings_name_id'), 'user_community_settings', ['name_id'], unique=False)
    op.create_index(op.f('ix_user_community_settings_user_id'), 'user_community_settings', ['user_id'], unique=False)
    op.create_table('voting_result',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('only_option_id', sa.String(), nullable=True),
                    sa.Column('member_id', sa.String(), nullable=False),
                    sa.Column('initiative_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['only_option_id'], ['voting_option.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voting_result_initiative_id'), 'voting_result', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_voting_result_member_id'), 'voting_result', ['member_id'], unique=False)
    op.create_index(op.f('ix_voting_result_only_option_id'), 'voting_result', ['only_option_id'], unique=False)
    op.create_table('community',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('main_settings_id', sa.String(), nullable=False),
                    sa.Column('creator_id', sa.String(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['main_settings_id'], ['community_settings.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_creator_id'), 'community', ['creator_id'], unique=False)
    op.create_index(op.f('ix_community_main_settings_id'), 'community', ['main_settings_id'], unique=False)
    op.create_table('delegate_settings',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('init_category_id', sa.String(), nullable=False),
                    sa.Column('user_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['init_category_id'], ['initiative_category.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegate_settings_init_category_id'), 'delegate_settings', ['init_category_id'], unique=False)
    op.create_index(op.f('ix_delegate_settings_user_id'), 'delegate_settings', ['user_id'], unique=False)
    op.create_table('initiative',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('type_id', sa.String(), nullable=False),
                    sa.Column('creator_id', sa.String(), nullable=False),
                    sa.Column('status_id', sa.String(), nullable=False),
                    sa.Column('category_id', sa.String(), nullable=False),
                    sa.Column('deadline', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['initiative_category.id'], ),
                    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
                    sa.ForeignKeyConstraint(['type_id'], ['initiative_type.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initiative_category_id'), 'initiative', ['category_id'], unique=False)
    op.create_index(op.f('ix_initiative_creator_id'), 'initiative', ['creator_id'], unique=False)
    op.create_index(op.f('ix_initiative_status_id'), 'initiative', ['status_id'], unique=False)
    op.create_index(op.f('ix_initiative_type_id'), 'initiative', ['type_id'], unique=False)
    op.create_table('relation_community_settings_categories',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('from_id', sa.String(), nullable=False),
                    sa.Column('to_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['from_id'], ['community_settings.id'], ),
                    sa.ForeignKeyConstraint(['to_id'], ['initiative_category.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_cs_init_category')
    )
    op.create_index(op.f('ix_relation_community_settings_categories_from_id'), 'relation_community_settings_categories', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_community_settings_categories_to_id'), 'relation_community_settings_categories', ['to_id'], unique=False)
    op.create_table('relation_opinion_like',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('from_id', sa.String(), nullable=False),
                    sa.Column('to_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['from_id'], ['opinion.id'], ),
                    sa.ForeignKeyConstraint(['to_id'], ['like.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_opinion_like')
    )
    op.create_index(op.f('ix_relation_opinion_like_from_id'), 'relation_opinion_like', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_opinion_like_to_id'), 'relation_opinion_like', ['to_id'], unique=False)
    op.create_table('relation_user_community_settings_categories',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('from_id', sa.String(), nullable=False),
                    sa.Column('to_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ),
                    sa.ForeignKeyConstraint(['to_id'], ['initiative_category.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_community_settings_init_categories')
    )
    op.create_index(op.f('ix_relation_user_community_settings_categories_from_id'), 'relation_user_community_settings_categories', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_community_settings_categories_to_id'), 'relation_user_community_settings_categories', ['to_id'], unique=False)
    op.create_table('relation_voting_result_voting_options',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('from_id', sa.String(), nullable=False),
                    sa.Column('to_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['from_id'], ['voting_result.id'], ),
                    sa.ForeignKeyConstraint(['to_id'], ['voting_option.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_voting_result_voting_option')
    )
    op.create_index(op.f('ix_relation_voting_result_voting_options_from_id'), 'relation_voting_result_voting_options', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_voting_result_voting_options_to_id'), 'relation_voting_result_voting_options', ['to_id'], unique=False)
    op.create_table('relation_community_user_community_settings',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('from_id', sa.String(), nullable=False),
                    sa.Column('to_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['from_id'], ['community.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['to_id'], ['user_community_settings.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_community_user_community_settings')
    )
    op.create_index(op.f('ix_relation_community_user_community_settings_from_id'), 'relation_community_user_community_settings', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_community_user_community_settings_to_id'), 'relation_community_user_community_settings', ['to_id'], unique=False)
    op.create_table('relation_delegate_settings_users',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('from_id', sa.String(), nullable=False),
                    sa.Column('to_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['from_id'], ['delegate_settings.id'], ),
                    sa.ForeignKeyConstraint(['to_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_delegate_settings_users')
    )
    op.create_index(op.f('ix_relation_delegate_settings_users_from_id'), 'relation_delegate_settings_users', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_delegate_settings_users_to_id'), 'relation_delegate_settings_users', ['to_id'], unique=False)
    op.create_table('relation_initiative_likes',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('from_id', sa.String(), nullable=False),
                    sa.Column('to_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['from_id'], ['initiative.id'], ),
                    sa.ForeignKeyConstraint(['to_id'], ['like.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_initiative_like')
    )
    op.create_index(op.f('ix_relation_initiative_likes_from_id'), 'relation_initiative_likes', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_initiative_likes_to_id'), 'relation_initiative_likes', ['to_id'], unique=False)
    op.create_table('relation_initiative_opinion',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('from_id', sa.String(), nullable=False),
                    sa.Column('to_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['from_id'], ['initiative.id'], ),
                    sa.ForeignKeyConstraint(['to_id'], ['opinion.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_initiative_opinion')
    )
    op.create_index(op.f('ix_relation_initiative_opinion_from_id'), 'relation_initiative_opinion', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_initiative_opinion_to_id'), 'relation_initiative_opinion', ['to_id'], unique=False)
    op.create_table('relation_initiative_voting_results',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('from_id', sa.String(), nullable=False),
                    sa.Column('to_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['from_id'], ['initiative.id'], ),
                    sa.ForeignKeyConstraint(['to_id'], ['voting_result.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_initiative_result_voting')
    )
    op.create_index(op.f('ix_relation_initiative_voting_results_from_id'), 'relation_initiative_voting_results', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_initiative_voting_results_to_id'), 'relation_initiative_voting_results', ['to_id'], unique=False)
    op.create_table('relation_user_community_settings_delegate_settings',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('from_id', sa.String(), nullable=False),
                    sa.Column('to_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ),
                    sa.ForeignKeyConstraint(['to_id'], ['delegate_settings.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_community_settings_delegate_settings')
    )
    op.create_index(op.f('ix_relation_user_community_settings_delegate_settings_from_id'), 'relation_user_community_settings_delegate_settings', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_community_settings_delegate_settings_to_id'), 'relation_user_community_settings_delegate_settings', ['to_id'], unique=False)
    op.create_table('request_member',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('member_id', sa.String(), nullable=True),
                    sa.Column('community_id', sa.String(), nullable=True),
                    sa.Column('status_id', sa.String(), nullable=False),
                    sa.Column('vote', sa.Boolean(), nullable=True),
                    sa.Column('reason', sa.String(), nullable=True),
                    sa.Column('parent_id', sa.String(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.Column('is_blocked', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
                    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_member_community_id'), 'request_member', ['community_id'], unique=False)
    op.create_index(op.f('ix_request_member_member_id'), 'request_member', ['member_id'], unique=False)
    op.create_index(op.f('ix_request_member_status_id'), 'request_member', ['status_id'], unique=False)
    op.create_table('relation_cs_request_member',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('from_id', sa.String(), nullable=False),
                    sa.Column('to_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['from_id'], ['community_settings.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['to_id'], ['request_member.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_community_settings_request_member')
    )
    op.create_index(op.f('ix_relation_cs_request_member_from_id'), 'relation_cs_request_member', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_cs_request_member_to_id'), 'relation_cs_request_member', ['to_id'], unique=False)
    op.create_table('relation_user_cs_request_member',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('from_id', sa.String(), nullable=False),
                    sa.Column('to_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['to_id'], ['request_member.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_community_settings_request_member')
    )
    op.create_index(op.f('ix_relation_user_cs_request_member_from_id'), 'relation_user_cs_request_member', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_cs_request_member_to_id'), 'relation_user_cs_request_member', ['to_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relation_user_cs_request_member_to_id'), table_name='relation_user_cs_request_member')
    op.drop_index(op.f('ix_relation_user_cs_request_member_from_id'), table_name='relation_user_cs_request_member')
    op.drop_table('relation_user_cs_request_member')
    op.drop_index(op.f('ix_relation_cs_request_member_to_id'), table_name='relation_cs_request_member')
    op.drop_index(op.f('ix_relation_cs_request_member_from_id'), table_name='relation_cs_request_member')
    op.drop_table('relation_cs_request_member')
    op.drop_index(op.f('ix_request_member_status_id'), table_name='request_member')
    op.drop_index(op.f('ix_request_member_member_id'), table_name='request_member')
    op.drop_index(op.f('ix_request_member_community_id'), table_name='request_member')
    op.drop_table('request_member')
    op.drop_index(op.f('ix_relation_user_community_settings_delegate_settings_to_id'), table_name='relation_user_community_settings_delegate_settings')
    op.drop_index(op.f('ix_relation_user_community_settings_delegate_settings_from_id'), table_name='relation_user_community_settings_delegate_settings')
    op.drop_table('relation_user_community_settings_delegate_settings')
    op.drop_index(op.f('ix_relation_initiative_voting_results_to_id'), table_name='relation_initiative_voting_results')
    op.drop_index(op.f('ix_relation_initiative_voting_results_from_id'), table_name='relation_initiative_voting_results')
    op.drop_table('relation_initiative_voting_results')
    op.drop_index(op.f('ix_relation_initiative_opinion_to_id'), table_name='relation_initiative_opinion')
    op.drop_index(op.f('ix_relation_initiative_opinion_from_id'), table_name='relation_initiative_opinion')
    op.drop_table('relation_initiative_opinion')
    op.drop_index(op.f('ix_relation_initiative_likes_to_id'), table_name='relation_initiative_likes')
    op.drop_index(op.f('ix_relation_initiative_likes_from_id'), table_name='relation_initiative_likes')
    op.drop_table('relation_initiative_likes')
    op.drop_index(op.f('ix_relation_delegate_settings_users_to_id'), table_name='relation_delegate_settings_users')
    op.drop_index(op.f('ix_relation_delegate_settings_users_from_id'), table_name='relation_delegate_settings_users')
    op.drop_table('relation_delegate_settings_users')
    op.drop_index(op.f('ix_relation_community_user_community_settings_to_id'), table_name='relation_community_user_community_settings')
    op.drop_index(op.f('ix_relation_community_user_community_settings_from_id'), table_name='relation_community_user_community_settings')
    op.drop_table('relation_community_user_community_settings')
    op.drop_index(op.f('ix_relation_voting_result_voting_options_to_id'), table_name='relation_voting_result_voting_options')
    op.drop_index(op.f('ix_relation_voting_result_voting_options_from_id'), table_name='relation_voting_result_voting_options')
    op.drop_table('relation_voting_result_voting_options')
    op.drop_index(op.f('ix_relation_user_community_settings_categories_to_id'), table_name='relation_user_community_settings_categories')
    op.drop_index(op.f('ix_relation_user_community_settings_categories_from_id'), table_name='relation_user_community_settings_categories')
    op.drop_table('relation_user_community_settings_categories')
    op.drop_index(op.f('ix_relation_opinion_like_to_id'), table_name='relation_opinion_like')
    op.drop_index(op.f('ix_relation_opinion_like_from_id'), table_name='relation_opinion_like')
    op.drop_table('relation_opinion_like')
    op.drop_index(op.f('ix_relation_community_settings_categories_to_id'), table_name='relation_community_settings_categories')
    op.drop_index(op.f('ix_relation_community_settings_categories_from_id'), table_name='relation_community_settings_categories')
    op.drop_table('relation_community_settings_categories')
    op.drop_index(op.f('ix_initiative_type_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_status_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_creator_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_category_id'), table_name='initiative')
    op.drop_table('initiative')
    op.drop_index(op.f('ix_delegate_settings_user_id'), table_name='delegate_settings')
    op.drop_index(op.f('ix_delegate_settings_init_category_id'), table_name='delegate_settings')
    op.drop_table('delegate_settings')
    op.drop_index(op.f('ix_community_main_settings_id'), table_name='community')
    op.drop_index(op.f('ix_community_creator_id'), table_name='community')
    op.drop_table('community')
    op.drop_index(op.f('ix_voting_result_only_option_id'), table_name='voting_result')
    op.drop_index(op.f('ix_voting_result_member_id'), table_name='voting_result')
    op.drop_index(op.f('ix_voting_result_initiative_id'), table_name='voting_result')
    op.drop_table('voting_result')
    op.drop_index(op.f('ix_user_community_settings_user_id'), table_name='user_community_settings')
    op.drop_index(op.f('ix_user_community_settings_name_id'), table_name='user_community_settings')
    op.drop_index(op.f('ix_user_community_settings_description_id'), table_name='user_community_settings')
    op.drop_index(op.f('ix_user_community_settings_community_id'), table_name='user_community_settings')
    op.drop_table('user_community_settings')
    op.drop_index(op.f('ix_opinion_initiative_id'), table_name='opinion')
    op.drop_index(op.f('ix_opinion_creator_id'), table_name='opinion')
    op.drop_table('opinion')
    op.drop_index(op.f('ix_initiative_category_status_id'), table_name='initiative_category')
    op.drop_index(op.f('ix_initiative_category_creator_id'), table_name='initiative_category')
    op.drop_index(op.f('ix_initiative_category_community_id'), table_name='initiative_category')
    op.drop_table('initiative_category')
    op.drop_index(op.f('ix_community_settings_name_id'), table_name='community_settings')
    op.drop_index(op.f('ix_community_settings_description_id'), table_name='community_settings')
    op.drop_table('community_settings')
    op.drop_index(op.f('ix_voting_option_initiative_id'), table_name='voting_option')
    op.drop_index(op.f('ix_voting_option_creator_id'), table_name='voting_option')
    op.drop_table('voting_option')
    op.drop_table('user')
    op.drop_table('status')
    op.drop_index(op.f('ix_like_opinion_id'), table_name='like')
    op.drop_index(op.f('ix_like_initiative_id'), table_name='like')
    op.drop_index(op.f('ix_like_creator_id'), table_name='like')
    op.drop_table('like')
    op.drop_table('initiative_type')
    op.drop_table('file_metadata')
    op.drop_index(op.f('ix_community_name_creator_id'), table_name='community_name')
    op.drop_index(op.f('ix_community_name_community_id'), table_name='community_name')
    op.drop_table('community_name')
    op.drop_index(op.f('ix_community_description_value'), table_name='community_description')
    op.drop_index(op.f('ix_community_description_creator_id'), table_name='community_description')
    op.drop_table('community_description')
    # ### end Alembic commands ###
