"""fix delegate settings tables

Revision ID: be24f46322a7
Revises: 14e73cc3ac0b
Create Date: 2024-04-08 21:46:34.505653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be24f46322a7'
down_revision: Union[str, None] = '14e73cc3ac0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delegate_settings', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_delegate_settings_user_id'), 'delegate_settings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'delegate_settings', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delegate_settings', type_='foreignkey')
    op.drop_index(op.f('ix_delegate_settings_user_id'), table_name='delegate_settings')
    op.drop_column('delegate_settings', 'user_id')
    # ### end Alembic commands ###
