"""Remove table member's request for removing

Revision ID: bf87a6b08448
Revises: 5b92ee695b57
Create Date: 2024-08-11 12:16:24.634301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf87a6b08448'
down_revision: Union[str, None] = '5b92ee695b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relation_cs_request_member_remove_from_id', table_name='relation_cs_request_member_remove')
    op.drop_index('ix_relation_cs_request_member_remove_to_id', table_name='relation_cs_request_member_remove')
    op.drop_table('relation_cs_request_member_remove')
    op.drop_column('request_member', 'is_removal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_member', sa.Column('is_removal', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_table('relation_cs_request_member_remove',
        sa.Column('from_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('to_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['from_id'], ['community_settings.id'], name='relation_cs_request_member_remove_from_id_fkey'),
        sa.ForeignKeyConstraint(['to_id'], ['request_member.id'], name='relation_cs_request_member_remove_to_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='relation_cs_request_member_remove_pkey'),
        sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_community_settings_request_member_remove')
    )
    op.create_index('ix_relation_cs_request_member_remove_to_id', 'relation_cs_request_member_remove', ['to_id'], unique=False)
    op.create_index('ix_relation_cs_request_member_remove_from_id', 'relation_cs_request_member_remove', ['from_id'], unique=False)
    # ### end Alembic commands ###
