"""init commit

Revision ID: c60a9cfd7708
Revises: 
Create Date: 2024-10-26 13:24:45.850008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60a9cfd7708'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('about_me', sa.String(), nullable=True),
    sa.Column('foto_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('community_description',
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value', 'community_id', name='idx_unique_community_description_id')
    )
    op.create_index(op.f('ix_community_description_creator_id'), 'community_description', ['creator_id'], unique=False)
    op.create_index(op.f('ix_community_description_value'), 'community_description', ['value'], unique=False)
    op.create_table('community_name',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'community_id', name='idx_unique_community_name_id')
    )
    op.create_index(op.f('ix_community_name_community_id'), 'community_name', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_name_creator_id'), 'community_name', ['creator_id'], unique=False)
    op.create_table('file_metadata',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('mimetype', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opinion',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opinion_creator_id'), 'opinion', ['creator_id'], unique=False)
    op.create_table('solution',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_creator_id'), 'solution', ['creator_id'], unique=False)
    op.create_table('status',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voting_option',
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_multi_select', sa.Boolean(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('initiative_id', sa.String(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voting_option_creator_id'), 'voting_option', ['creator_id'], unique=False)
    op.create_index(op.f('ix_voting_option_initiative_id'), 'voting_option', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_voting_option_rule_id'), 'voting_option', ['rule_id'], unique=False)
    op.create_table('voting_result',
    sa.Column('vote', sa.Boolean(), nullable=True),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('initiative_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voting_result_initiative_id'), 'voting_result', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_voting_result_member_id'), 'voting_result', ['member_id'], unique=False)
    op.create_table('auth_user_data',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_data_user_id'), 'auth_user_data', ['user_id'], unique=False)
    op.create_table('category',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_community_id'), 'category', ['community_id'], unique=False)
    op.create_index(op.f('ix_category_creator_id'), 'category', ['creator_id'], unique=False)
    op.create_index(op.f('ix_category_status_id'), 'category', ['status_id'], unique=False)
    op.create_table('community_settings',
    sa.Column('name_id', sa.String(), nullable=True),
    sa.Column('description_id', sa.String(), nullable=True),
    sa.Column('quorum', sa.Integer(), nullable=True),
    sa.Column('vote', sa.Integer(), nullable=True),
    sa.Column('is_secret_ballot', sa.Boolean(), nullable=False),
    sa.Column('is_can_offer', sa.Boolean(), nullable=False),
    sa.Column('is_minority_not_participate', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['description_id'], ['community_description.id'], ),
    sa.ForeignKeyConstraint(['name_id'], ['community_name.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_settings_description_id'), 'community_settings', ['description_id'], unique=False)
    op.create_index(op.f('ix_community_settings_name_id'), 'community_settings', ['name_id'], unique=False)
    op.create_table('relation_voting_result_voting_options',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['voting_result.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['voting_option.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_voting_result_voting_option')
    )
    op.create_index(op.f('ix_relation_voting_result_voting_options_from_id'), 'relation_voting_result_voting_options', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_voting_result_voting_options_to_id'), 'relation_voting_result_voting_options', ['to_id'], unique=False)
    op.create_table('user_community_settings',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('name_id', sa.String(), nullable=False),
    sa.Column('description_id', sa.String(), nullable=False),
    sa.Column('quorum', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.Column('is_secret_ballot', sa.Boolean(), nullable=False),
    sa.Column('is_can_offer', sa.Boolean(), nullable=False),
    sa.Column('is_minority_not_participate', sa.Boolean(), nullable=False),
    sa.Column('is_not_delegate', sa.Boolean(), nullable=False),
    sa.Column('is_default_add_member', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['description_id'], ['community_description.id'], ),
    sa.ForeignKeyConstraint(['name_id'], ['community_name.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'community_id', name='idx_unique_user_cs_community_user')
    )
    op.create_index(op.f('ix_user_community_settings_community_id'), 'user_community_settings', ['community_id'], unique=False)
    op.create_index(op.f('ix_user_community_settings_description_id'), 'user_community_settings', ['description_id'], unique=False)
    op.create_index(op.f('ix_user_community_settings_name_id'), 'user_community_settings', ['name_id'], unique=False)
    op.create_index(op.f('ix_user_community_settings_user_id'), 'user_community_settings', ['user_id'], unique=False)
    op.create_table('challenge',
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_category_id'), 'challenge', ['category_id'], unique=False)
    op.create_index(op.f('ix_challenge_community_id'), 'challenge', ['community_id'], unique=False)
    op.create_index(op.f('ix_challenge_creator_id'), 'challenge', ['creator_id'], unique=False)
    op.create_index(op.f('ix_challenge_status_id'), 'challenge', ['status_id'], unique=False)
    op.create_table('community',
    sa.Column('main_settings_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['main_settings_id'], ['community_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_creator_id'), 'community', ['creator_id'], unique=False)
    op.create_index(op.f('ix_community_main_settings_id'), 'community', ['main_settings_id'], unique=False)
    op.create_table('delegate_settings',
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegate_settings_category_id'), 'delegate_settings', ['category_id'], unique=False)
    op.create_index(op.f('ix_delegate_settings_user_id'), 'delegate_settings', ['user_id'], unique=False)
    op.create_table('initiative',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_extra_options', sa.Boolean(), nullable=False),
    sa.Column('is_multi_select', sa.Boolean(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('responsible_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initiative_category_id'), 'initiative', ['category_id'], unique=False)
    op.create_index(op.f('ix_initiative_community_id'), 'initiative', ['community_id'], unique=False)
    op.create_index(op.f('ix_initiative_creator_id'), 'initiative', ['creator_id'], unique=False)
    op.create_index(op.f('ix_initiative_responsible_id'), 'initiative', ['responsible_id'], unique=False)
    op.create_index(op.f('ix_initiative_status_id'), 'initiative', ['status_id'], unique=False)
    op.create_table('relation_community_settings_categories',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['community_settings.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_cs_category')
    )
    op.create_index(op.f('ix_relation_community_settings_categories_from_id'), 'relation_community_settings_categories', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_community_settings_categories_to_id'), 'relation_community_settings_categories', ['to_id'], unique=False)
    op.create_table('relation_user_community_settings_categories',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_community_settings_categories')
    )
    op.create_index(op.f('ix_relation_user_community_settings_categories_from_id'), 'relation_user_community_settings_categories', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_community_settings_categories_to_id'), 'relation_user_community_settings_categories', ['to_id'], unique=False)
    op.create_table('rule',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_extra_options', sa.Boolean(), nullable=False),
    sa.Column('is_multi_select', sa.Boolean(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_category_id'), 'rule', ['category_id'], unique=False)
    op.create_index(op.f('ix_rule_community_id'), 'rule', ['community_id'], unique=False)
    op.create_index(op.f('ix_rule_creator_id'), 'rule', ['creator_id'], unique=False)
    op.create_index(op.f('ix_rule_status_id'), 'rule', ['status_id'], unique=False)
    op.create_table('relation_challenge_solutions',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['challenge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['solution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_challenge_solutions')
    )
    op.create_index(op.f('ix_relation_challenge_solutions_from_id'), 'relation_challenge_solutions', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_challenge_solutions_to_id'), 'relation_challenge_solutions', ['to_id'], unique=False)
    op.create_table('relation_community_user_community_settings',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['user_community_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_community_user_community_settings')
    )
    op.create_index(op.f('ix_relation_community_user_community_settings_from_id'), 'relation_community_user_community_settings', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_community_user_community_settings_to_id'), 'relation_community_user_community_settings', ['to_id'], unique=False)
    op.create_table('relation_delegate_settings_users',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['delegate_settings.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_delegate_settings_users')
    )
    op.create_index(op.f('ix_relation_delegate_settings_users_from_id'), 'relation_delegate_settings_users', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_delegate_settings_users_to_id'), 'relation_delegate_settings_users', ['to_id'], unique=False)
    op.create_table('relation_initiative_opinion',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['initiative.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['opinion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_initiative_opinion')
    )
    op.create_index(op.f('ix_relation_initiative_opinion_from_id'), 'relation_initiative_opinion', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_initiative_opinion_to_id'), 'relation_initiative_opinion', ['to_id'], unique=False)
    op.create_table('relation_initiative_voting_options',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['initiative.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['voting_option.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_initiative_voting_options')
    )
    op.create_index(op.f('ix_relation_initiative_voting_options_from_id'), 'relation_initiative_voting_options', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_initiative_voting_options_to_id'), 'relation_initiative_voting_options', ['to_id'], unique=False)
    op.create_table('relation_initiative_voting_results',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['initiative.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['voting_result.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_initiative_voting_results')
    )
    op.create_index(op.f('ix_relation_initiative_voting_results_from_id'), 'relation_initiative_voting_results', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_initiative_voting_results_to_id'), 'relation_initiative_voting_results', ['to_id'], unique=False)
    op.create_table('relation_rule_opinion',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['rule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['opinion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_rule_opinion')
    )
    op.create_index(op.f('ix_relation_rule_opinion_from_id'), 'relation_rule_opinion', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_rule_opinion_to_id'), 'relation_rule_opinion', ['to_id'], unique=False)
    op.create_table('relation_rule_voting_options',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['rule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['voting_option.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_rule_voting_options')
    )
    op.create_index(op.f('ix_relation_rule_voting_options_from_id'), 'relation_rule_voting_options', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_rule_voting_options_to_id'), 'relation_rule_voting_options', ['to_id'], unique=False)
    op.create_table('relation_rule_voting_results',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['rule.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['voting_result.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_rule_voting_results')
    )
    op.create_index(op.f('ix_relation_rule_voting_results_from_id'), 'relation_rule_voting_results', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_rule_voting_results_to_id'), 'relation_rule_voting_results', ['to_id'], unique=False)
    op.create_table('relation_user_community_settings_delegate_settings',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['delegate_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_community_settings_delegate_settings')
    )
    op.create_index(op.f('ix_relation_user_community_settings_delegate_settings_from_id'), 'relation_user_community_settings_delegate_settings', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_community_settings_delegate_settings_to_id'), 'relation_user_community_settings_delegate_settings', ['to_id'], unique=False)
    op.create_table('request_member',
    sa.Column('member_id', sa.String(), nullable=True),
    sa.Column('community_id', sa.String(), nullable=True),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('vote', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_member_community_id'), 'request_member', ['community_id'], unique=False)
    op.create_index(op.f('ix_request_member_member_id'), 'request_member', ['member_id'], unique=False)
    op.create_index(op.f('ix_request_member_status_id'), 'request_member', ['status_id'], unique=False)
    op.create_table('relation_cs_request_member',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['community_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['request_member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_community_settings_request_member')
    )
    op.create_index(op.f('ix_relation_cs_request_member_from_id'), 'relation_cs_request_member', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_cs_request_member_to_id'), 'relation_cs_request_member', ['to_id'], unique=False)
    op.create_table('relation_user_cs_request_member',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['request_member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_community_settings_request_member')
    )
    op.create_index(op.f('ix_relation_user_cs_request_member_from_id'), 'relation_user_cs_request_member', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_cs_request_member_to_id'), 'relation_user_cs_request_member', ['to_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relation_user_cs_request_member_to_id'), table_name='relation_user_cs_request_member')
    op.drop_index(op.f('ix_relation_user_cs_request_member_from_id'), table_name='relation_user_cs_request_member')
    op.drop_table('relation_user_cs_request_member')
    op.drop_index(op.f('ix_relation_cs_request_member_to_id'), table_name='relation_cs_request_member')
    op.drop_index(op.f('ix_relation_cs_request_member_from_id'), table_name='relation_cs_request_member')
    op.drop_table('relation_cs_request_member')
    op.drop_index(op.f('ix_request_member_status_id'), table_name='request_member')
    op.drop_index(op.f('ix_request_member_member_id'), table_name='request_member')
    op.drop_index(op.f('ix_request_member_community_id'), table_name='request_member')
    op.drop_table('request_member')
    op.drop_index(op.f('ix_relation_user_community_settings_delegate_settings_to_id'), table_name='relation_user_community_settings_delegate_settings')
    op.drop_index(op.f('ix_relation_user_community_settings_delegate_settings_from_id'), table_name='relation_user_community_settings_delegate_settings')
    op.drop_table('relation_user_community_settings_delegate_settings')
    op.drop_index(op.f('ix_relation_rule_voting_results_to_id'), table_name='relation_rule_voting_results')
    op.drop_index(op.f('ix_relation_rule_voting_results_from_id'), table_name='relation_rule_voting_results')
    op.drop_table('relation_rule_voting_results')
    op.drop_index(op.f('ix_relation_rule_voting_options_to_id'), table_name='relation_rule_voting_options')
    op.drop_index(op.f('ix_relation_rule_voting_options_from_id'), table_name='relation_rule_voting_options')
    op.drop_table('relation_rule_voting_options')
    op.drop_index(op.f('ix_relation_rule_opinion_to_id'), table_name='relation_rule_opinion')
    op.drop_index(op.f('ix_relation_rule_opinion_from_id'), table_name='relation_rule_opinion')
    op.drop_table('relation_rule_opinion')
    op.drop_index(op.f('ix_relation_initiative_voting_results_to_id'), table_name='relation_initiative_voting_results')
    op.drop_index(op.f('ix_relation_initiative_voting_results_from_id'), table_name='relation_initiative_voting_results')
    op.drop_table('relation_initiative_voting_results')
    op.drop_index(op.f('ix_relation_initiative_voting_options_to_id'), table_name='relation_initiative_voting_options')
    op.drop_index(op.f('ix_relation_initiative_voting_options_from_id'), table_name='relation_initiative_voting_options')
    op.drop_table('relation_initiative_voting_options')
    op.drop_index(op.f('ix_relation_initiative_opinion_to_id'), table_name='relation_initiative_opinion')
    op.drop_index(op.f('ix_relation_initiative_opinion_from_id'), table_name='relation_initiative_opinion')
    op.drop_table('relation_initiative_opinion')
    op.drop_index(op.f('ix_relation_delegate_settings_users_to_id'), table_name='relation_delegate_settings_users')
    op.drop_index(op.f('ix_relation_delegate_settings_users_from_id'), table_name='relation_delegate_settings_users')
    op.drop_table('relation_delegate_settings_users')
    op.drop_index(op.f('ix_relation_community_user_community_settings_to_id'), table_name='relation_community_user_community_settings')
    op.drop_index(op.f('ix_relation_community_user_community_settings_from_id'), table_name='relation_community_user_community_settings')
    op.drop_table('relation_community_user_community_settings')
    op.drop_index(op.f('ix_relation_challenge_solutions_to_id'), table_name='relation_challenge_solutions')
    op.drop_index(op.f('ix_relation_challenge_solutions_from_id'), table_name='relation_challenge_solutions')
    op.drop_table('relation_challenge_solutions')
    op.drop_index(op.f('ix_rule_status_id'), table_name='rule')
    op.drop_index(op.f('ix_rule_creator_id'), table_name='rule')
    op.drop_index(op.f('ix_rule_community_id'), table_name='rule')
    op.drop_index(op.f('ix_rule_category_id'), table_name='rule')
    op.drop_table('rule')
    op.drop_index(op.f('ix_relation_user_community_settings_categories_to_id'), table_name='relation_user_community_settings_categories')
    op.drop_index(op.f('ix_relation_user_community_settings_categories_from_id'), table_name='relation_user_community_settings_categories')
    op.drop_table('relation_user_community_settings_categories')
    op.drop_index(op.f('ix_relation_community_settings_categories_to_id'), table_name='relation_community_settings_categories')
    op.drop_index(op.f('ix_relation_community_settings_categories_from_id'), table_name='relation_community_settings_categories')
    op.drop_table('relation_community_settings_categories')
    op.drop_index(op.f('ix_initiative_status_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_responsible_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_creator_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_community_id'), table_name='initiative')
    op.drop_index(op.f('ix_initiative_category_id'), table_name='initiative')
    op.drop_table('initiative')
    op.drop_index(op.f('ix_delegate_settings_user_id'), table_name='delegate_settings')
    op.drop_index(op.f('ix_delegate_settings_category_id'), table_name='delegate_settings')
    op.drop_table('delegate_settings')
    op.drop_index(op.f('ix_community_main_settings_id'), table_name='community')
    op.drop_index(op.f('ix_community_creator_id'), table_name='community')
    op.drop_table('community')
    op.drop_index(op.f('ix_challenge_status_id'), table_name='challenge')
    op.drop_index(op.f('ix_challenge_creator_id'), table_name='challenge')
    op.drop_index(op.f('ix_challenge_community_id'), table_name='challenge')
    op.drop_index(op.f('ix_challenge_category_id'), table_name='challenge')
    op.drop_table('challenge')
    op.drop_index(op.f('ix_user_community_settings_user_id'), table_name='user_community_settings')
    op.drop_index(op.f('ix_user_community_settings_name_id'), table_name='user_community_settings')
    op.drop_index(op.f('ix_user_community_settings_description_id'), table_name='user_community_settings')
    op.drop_index(op.f('ix_user_community_settings_community_id'), table_name='user_community_settings')
    op.drop_table('user_community_settings')
    op.drop_index(op.f('ix_relation_voting_result_voting_options_to_id'), table_name='relation_voting_result_voting_options')
    op.drop_index(op.f('ix_relation_voting_result_voting_options_from_id'), table_name='relation_voting_result_voting_options')
    op.drop_table('relation_voting_result_voting_options')
    op.drop_index(op.f('ix_community_settings_name_id'), table_name='community_settings')
    op.drop_index(op.f('ix_community_settings_description_id'), table_name='community_settings')
    op.drop_table('community_settings')
    op.drop_index(op.f('ix_category_status_id'), table_name='category')
    op.drop_index(op.f('ix_category_creator_id'), table_name='category')
    op.drop_index(op.f('ix_category_community_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_auth_user_data_user_id'), table_name='auth_user_data')
    op.drop_table('auth_user_data')
    op.drop_index(op.f('ix_voting_result_member_id'), table_name='voting_result')
    op.drop_index(op.f('ix_voting_result_initiative_id'), table_name='voting_result')
    op.drop_table('voting_result')
    op.drop_index(op.f('ix_voting_option_rule_id'), table_name='voting_option')
    op.drop_index(op.f('ix_voting_option_initiative_id'), table_name='voting_option')
    op.drop_index(op.f('ix_voting_option_creator_id'), table_name='voting_option')
    op.drop_table('voting_option')
    op.drop_table('status')
    op.drop_index(op.f('ix_solution_creator_id'), table_name='solution')
    op.drop_table('solution')
    op.drop_index(op.f('ix_opinion_creator_id'), table_name='opinion')
    op.drop_table('opinion')
    op.drop_table('file_metadata')
    op.drop_index(op.f('ix_community_name_creator_id'), table_name='community_name')
    op.drop_index(op.f('ix_community_name_community_id'), table_name='community_name')
    op.drop_table('community_name')
    op.drop_index(op.f('ix_community_description_value'), table_name='community_description')
    op.drop_index(op.f('ix_community_description_creator_id'), table_name='community_description')
    op.drop_table('community_description')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
