"""fix rule table

Revision ID: c7f25883767a
Revises: d9b2697815c7
Create Date: 2025-02-23 22:04:49.533893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f25883767a'
down_revision: Union[str, None] = 'd9b2697815c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('extra_question', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule', 'extra_question')
    # ### end Alembic commands ###
