"""init tables 2

Revision ID: ca0c6c32a559
Revises: 2a3bd8705d7e
Create Date: 2024-03-19 22:19:57.408942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0c6c32a559'
down_revision: Union[str, None] = '2a3bd8705d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_settings',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user', sa.String(), nullable=True),
        sa.Column('community', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('quorum', sa.Integer(), nullable=False),
        sa.Column('vote', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['community'], ['community.id'], ),
        sa.ForeignKeyConstraint(['user'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_settings_community'), 'community_settings', ['community'], unique=False)
    op.create_index(op.f('ix_community_settings_user'), 'community_settings', ['user'], unique=False)
    op.add_column('community', sa.Column('main_settings', sa.String(), nullable=False))
    op.create_index(op.f('ix_community_main_settings'), 'community', ['main_settings'], unique=False)
    op.create_foreign_key(None, 'community', 'community_settings', ['main_settings'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'community', type_='foreignkey')
    op.drop_index(op.f('ix_community_main_settings'), table_name='community')
    op.drop_column('community', 'main_settings')
    op.drop_index(op.f('ix_community_settings_user'), table_name='community_settings')
    op.drop_index(op.f('ix_community_settings_community'), table_name='community_settings')
    op.drop_table('community_settings')
    # ### end Alembic commands ###
