"""fix relations

Revision ID: cea4cb7bc3ed
Revises: 5067f5fe6992
Create Date: 2025-07-23 17:40:58.946687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea4cb7bc3ed'
down_revision: Union[str, None] = '5067f5fe6992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('relation_ucs_descriptions_from_id_fkey', 'relation_ucs_descriptions', type_='foreignkey')
    op.drop_constraint('relation_ucs_descriptions_to_id_fkey', 'relation_ucs_descriptions', type_='foreignkey')
    op.create_foreign_key(None, 'relation_ucs_descriptions', 'user_community_settings', ['from_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relation_ucs_descriptions', 'community_description', ['to_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('relation_ucs_names_from_id_fkey', 'relation_ucs_names', type_='foreignkey')
    op.drop_constraint('relation_ucs_names_to_id_fkey', 'relation_ucs_names', type_='foreignkey')
    op.create_foreign_key(None, 'relation_ucs_names', 'community_name', ['to_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relation_ucs_names', 'user_community_settings', ['from_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('relation_user_community_settings_responsibilities_from_id_fkey', 'relation_user_community_settings_responsibilities', type_='foreignkey')
    op.drop_constraint('relation_user_community_settings_responsibilities_to_id_fkey', 'relation_user_community_settings_responsibilities', type_='foreignkey')
    op.create_foreign_key(None, 'relation_user_community_settings_responsibilities', 'user_community_settings', ['from_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relation_user_community_settings_responsibilities', 'responsibility', ['to_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('relation_user_community_settings_user_cs_to_id_fkey', 'relation_user_community_settings_user_cs', type_='foreignkey')
    op.drop_constraint('relation_user_community_settings_user_cs_from_id_fkey', 'relation_user_community_settings_user_cs', type_='foreignkey')
    op.create_foreign_key(None, 'relation_user_community_settings_user_cs', 'user_community_settings', ['from_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relation_user_community_settings_user_cs', 'user_community_settings', ['to_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relation_user_community_settings_user_cs', type_='foreignkey')
    op.drop_constraint(None, 'relation_user_community_settings_user_cs', type_='foreignkey')
    op.create_foreign_key('relation_user_community_settings_user_cs_from_id_fkey', 'relation_user_community_settings_user_cs', 'user_community_settings', ['from_id'], ['id'])
    op.create_foreign_key('relation_user_community_settings_user_cs_to_id_fkey', 'relation_user_community_settings_user_cs', 'user_community_settings', ['to_id'], ['id'])
    op.drop_constraint(None, 'relation_user_community_settings_responsibilities', type_='foreignkey')
    op.drop_constraint(None, 'relation_user_community_settings_responsibilities', type_='foreignkey')
    op.create_foreign_key('relation_user_community_settings_responsibilities_to_id_fkey', 'relation_user_community_settings_responsibilities', 'responsibility', ['to_id'], ['id'])
    op.create_foreign_key('relation_user_community_settings_responsibilities_from_id_fkey', 'relation_user_community_settings_responsibilities', 'user_community_settings', ['from_id'], ['id'])
    op.drop_constraint(None, 'relation_ucs_names', type_='foreignkey')
    op.drop_constraint(None, 'relation_ucs_names', type_='foreignkey')
    op.create_foreign_key('relation_ucs_names_to_id_fkey', 'relation_ucs_names', 'community_name', ['to_id'], ['id'])
    op.create_foreign_key('relation_ucs_names_from_id_fkey', 'relation_ucs_names', 'user_community_settings', ['from_id'], ['id'])
    op.drop_constraint(None, 'relation_ucs_descriptions', type_='foreignkey')
    op.drop_constraint(None, 'relation_ucs_descriptions', type_='foreignkey')
    op.create_foreign_key('relation_ucs_descriptions_to_id_fkey', 'relation_ucs_descriptions', 'community_description', ['to_id'], ['id'])
    op.create_foreign_key('relation_ucs_descriptions_from_id_fkey', 'relation_ucs_descriptions', 'user_community_settings', ['from_id'], ['id'])
    # ### end Alembic commands ###
