"""add some relations tables

Revision ID: d23b6d1d64ae
Revises: e2ed3225d7db
Create Date: 2024-04-25 22:13:02.878007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23b6d1d64ae'
down_revision: Union[str, None] = 'e2ed3225d7db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_cs_request_member',
        sa.Column('from_id', sa.String(), nullable=False),
        sa.Column('to_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['from_id'], ['community_settings.id'], ),
        sa.ForeignKeyConstraint(['to_id'], ['request_member.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_community_settings_request_member')
    )
    op.create_index(op.f('ix_relation_cs_request_member_from_id'), 'relation_cs_request_member', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_cs_request_member_to_id'), 'relation_cs_request_member', ['to_id'], unique=False)
    op.create_table('relation_cs_request_member_remove',
        sa.Column('from_id', sa.String(), nullable=False),
        sa.Column('to_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['from_id'], ['community_settings.id'], ),
        sa.ForeignKeyConstraint(['to_id'], ['request_member.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_community_settings_request_member_remove')
    )
    op.create_index(op.f('ix_relation_cs_request_member_remove_from_id'), 'relation_cs_request_member_remove', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_cs_request_member_remove_to_id'), 'relation_cs_request_member_remove', ['to_id'], unique=False)
    op.create_table('relation_user_cs_request_member',
        sa.Column('from_id', sa.String(), nullable=False),
        sa.Column('to_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ),
        sa.ForeignKeyConstraint(['to_id'], ['request_member.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_community_settings_request_member')
    )
    op.create_index(op.f('ix_relation_user_cs_request_member_from_id'), 'relation_user_cs_request_member', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_cs_request_member_to_id'), 'relation_user_cs_request_member', ['to_id'], unique=False)
    op.create_table('relation_user_cs_request_member_remove',
        sa.Column('from_id', sa.String(), nullable=False),
        sa.Column('to_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['from_id'], ['user_community_settings.id'], ),
        sa.ForeignKeyConstraint(['to_id'], ['request_member.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_community_settings_request_member_remove')
    )
    op.create_index(op.f('ix_relation_user_cs_request_member_remove_from_id'), 'relation_user_cs_request_member_remove', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_cs_request_member_remove_to_id'), 'relation_user_cs_request_member_remove', ['to_id'], unique=False)
    op.create_table('relation_user_request_member',
        sa.Column('from_id', sa.String(), nullable=False),
        sa.Column('to_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['from_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['to_id'], ['request_member.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_request_member')
    )
    op.create_index(op.f('ix_relation_user_request_member_from_id'), 'relation_user_request_member', ['from_id'], unique=False)
    op.create_index(op.f('ix_relation_user_request_member_to_id'), 'relation_user_request_member', ['to_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relation_user_request_member_to_id'), table_name='relation_user_request_member')
    op.drop_index(op.f('ix_relation_user_request_member_from_id'), table_name='relation_user_request_member')
    op.drop_table('relation_user_request_member')
    op.drop_index(op.f('ix_relation_user_cs_request_member_remove_to_id'), table_name='relation_user_cs_request_member_remove')
    op.drop_index(op.f('ix_relation_user_cs_request_member_remove_from_id'), table_name='relation_user_cs_request_member_remove')
    op.drop_table('relation_user_cs_request_member_remove')
    op.drop_index(op.f('ix_relation_user_cs_request_member_to_id'), table_name='relation_user_cs_request_member')
    op.drop_index(op.f('ix_relation_user_cs_request_member_from_id'), table_name='relation_user_cs_request_member')
    op.drop_table('relation_user_cs_request_member')
    op.drop_index(op.f('ix_relation_cs_request_member_remove_to_id'), table_name='relation_cs_request_member_remove')
    op.drop_index(op.f('ix_relation_cs_request_member_remove_from_id'), table_name='relation_cs_request_member_remove')
    op.drop_table('relation_cs_request_member_remove')
    op.drop_index(op.f('ix_relation_cs_request_member_to_id'), table_name='relation_cs_request_member')
    op.drop_index(op.f('ix_relation_cs_request_member_from_id'), table_name='relation_cs_request_member')
    op.drop_table('relation_cs_request_member')
    # ### end Alembic commands ###
