"""add relation tables

Revision ID: d5755b584563
Revises: 86187b2b15e0
Create Date: 2024-04-06 14:30:35.256894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5755b584563'
down_revision: Union[str, None] = '86187b2b15e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegate_settings',
        sa.Column('init_category_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['init_category_id'], ['initiative_category.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegate_settings_init_category_id'), 'delegate_settings', ['init_category_id'], unique=False)
    op.create_table('relation_cs_ds',
        sa.Column('cs_id', sa.String(), nullable=False),
        sa.Column('ds_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['cs_id'], ['community_settings.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['ds_id'], ['delegate_settings.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cs_id', 'ds_id', name='idx_unique_cs_ds')
    )
    op.create_index(op.f('ix_relation_cs_ds_cs_id'), 'relation_cs_ds', ['cs_id'], unique=False)
    op.create_index(op.f('ix_relation_cs_ds_ds_id'), 'relation_cs_ds', ['ds_id'], unique=False)
    op.create_table('relation_ds_users',
        sa.Column('ds_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['ds_id'], ['delegate_settings.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ds_id', 'user_id', name='idx_unique_ds_user')
    )
    op.create_index(op.f('ix_relation_ds_users_ds_id'), 'relation_ds_users', ['ds_id'], unique=False)
    op.create_index(op.f('ix_relation_ds_users_user_id'), 'relation_ds_users', ['user_id'], unique=False)
    op.create_table('relation_initiative_voting_results',
        sa.Column('initiative_id', sa.String(), nullable=False),
        sa.Column('result_voting_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['initiative_id'], ['initiative.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['result_voting_id'], ['result_voting.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('initiative_id', 'result_voting_id', name='idx_unique_initiative_result_voting')
    )
    op.create_index(op.f('ix_relation_initiative_voting_results_initiative_id'), 'relation_initiative_voting_results', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_relation_initiative_voting_results_result_voting_id'), 'relation_initiative_voting_results', ['result_voting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relation_initiative_voting_results_result_voting_id'), table_name='relation_initiative_voting_results')
    op.drop_index(op.f('ix_relation_initiative_voting_results_initiative_id'), table_name='relation_initiative_voting_results')
    op.drop_table('relation_initiative_voting_results')
    op.drop_index(op.f('ix_relation_ds_users_user_id'), table_name='relation_ds_users')
    op.drop_index(op.f('ix_relation_ds_users_ds_id'), table_name='relation_ds_users')
    op.drop_table('relation_ds_users')
    op.drop_index(op.f('ix_relation_cs_ds_ds_id'), table_name='relation_cs_ds')
    op.drop_index(op.f('ix_relation_cs_ds_cs_id'), table_name='relation_cs_ds')
    op.drop_table('relation_cs_ds')
    op.drop_index(op.f('ix_delegate_settings_init_category_id'), table_name='delegate_settings')
    op.drop_table('delegate_settings')
    # ### end Alembic commands ###
