"""add request member table

Revision ID: e2ed3225d7db
Revises: 972b9ff49f56
Create Date: 2024-04-25 21:11:41.254528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ed3225d7db'
down_revision: Union[str, None] = '972b9ff49f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_member',
        sa.Column('member_id', sa.String(), nullable=True),
        sa.Column('creator_id', sa.String(), nullable=True),
        sa.Column('community_id', sa.String(), nullable=True),
        sa.Column('status_id', sa.String(), nullable=False),
        sa.Column('vote', sa.Boolean(), nullable=True),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('is_removal', sa.Boolean(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
        sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('member_id', 'community_id', name='idx_unique_request_member_community')
    )
    op.create_index(op.f('ix_request_member_community_id'), 'request_member', ['community_id'], unique=False)
    op.create_index(op.f('ix_request_member_creator_id'), 'request_member', ['creator_id'], unique=False)
    op.create_index(op.f('ix_request_member_member_id'), 'request_member', ['member_id'], unique=False)
    op.create_index(op.f('ix_request_member_status_id'), 'request_member', ['status_id'], unique=False)
    op.alter_column('community_description', 'is_readonly',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('community_name', 'is_readonly',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('community_settings', 'is_minority_not_participate',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_community_settings', 'is_minority_not_participate',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_community_settings', 'is_minority_not_participate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('community_settings', 'is_minority_not_participate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('community_name', 'is_readonly',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('community_description', 'is_readonly',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_request_member_status_id'), table_name='request_member')
    op.drop_index(op.f('ix_request_member_member_id'), table_name='request_member')
    op.drop_index(op.f('ix_request_member_creator_id'), table_name='request_member')
    op.drop_index(op.f('ix_request_member_community_id'), table_name='request_member')
    op.drop_table('request_member')
    # ### end Alembic commands ###
