"""Remove RelationUserRequestMember table

Revision ID: e6e881f56851
Revises: 66a5fcdbef70
Create Date: 2024-08-25 21:28:25.145965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e881f56851'
down_revision: Union[str, None] = '66a5fcdbef70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relation_user_request_member_from_id', table_name='relation_user_request_member')
    op.drop_index('ix_relation_user_request_member_to_id', table_name='relation_user_request_member')
    op.drop_table('relation_user_request_member')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_user_request_member',
        sa.Column('from_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('to_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['from_id'], ['user.id'], name='relation_user_request_member_from_id_fkey'),
        sa.ForeignKeyConstraint(['to_id'], ['request_member.id'], name='relation_user_request_member_to_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='relation_user_request_member_pkey'),
        sa.UniqueConstraint('from_id', 'to_id', name='idx_unique_user_request_member')
    )
    op.create_index('ix_relation_user_request_member_to_id', 'relation_user_request_member', ['to_id'], unique=False)
    op.create_index('ix_relation_user_request_member_from_id', 'relation_user_request_member', ['from_id'], unique=False)
    # ### end Alembic commands ###
