"""add tables for community settings

Revision ID: fbdac374b3ec
Revises: 05cd372ef58c
Create Date: 2024-04-21 00:46:20.551631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbdac374b3ec'
down_revision: Union[str, None] = '05cd372ef58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_description',
        sa.Column('value', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('community_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_name',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('community_id', sa.String(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('community_settings', sa.Column('name_id', sa.String(), nullable=False))
    op.add_column('community_settings', sa.Column('description_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_community_settings_description_id'), 'community_settings', ['description_id'], unique=False)
    op.create_index(op.f('ix_community_settings_name_id'), 'community_settings', ['name_id'], unique=False)
    op.create_foreign_key(None, 'community_settings', 'community_name', ['name_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'community_settings', 'community_description', ['description_id'], ['id'], ondelete='CASCADE')
    op.drop_column('community_settings', 'name')
    op.drop_constraint('idx_unique_file_metadata_path', 'file_metadata', type_='unique')
    op.add_column('user_community_settings', sa.Column('name_id', sa.String(), nullable=False))
    op.add_column('user_community_settings', sa.Column('description_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_user_community_settings_description_id'), 'user_community_settings', ['description_id'], unique=False)
    op.create_index(op.f('ix_user_community_settings_name_id'), 'user_community_settings', ['name_id'], unique=False)
    op.create_foreign_key(None, 'user_community_settings', 'community_name', ['name_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_community_settings', 'community_description', ['description_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_community_settings', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_community_settings', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_community_settings', type_='foreignkey')
    op.drop_constraint(None, 'user_community_settings', type_='foreignkey')
    op.drop_index(op.f('ix_user_community_settings_name_id'), table_name='user_community_settings')
    op.drop_index(op.f('ix_user_community_settings_description_id'), table_name='user_community_settings')
    op.drop_column('user_community_settings', 'description_id')
    op.drop_column('user_community_settings', 'name_id')
    op.create_unique_constraint('idx_unique_file_metadata_path', 'file_metadata', ['id', 'path'])
    op.add_column('community_settings', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'community_settings', type_='foreignkey')
    op.drop_constraint(None, 'community_settings', type_='foreignkey')
    op.drop_index(op.f('ix_community_settings_name_id'), table_name='community_settings')
    op.drop_index(op.f('ix_community_settings_description_id'), table_name='community_settings')
    op.drop_column('community_settings', 'description_id')
    op.drop_column('community_settings', 'name_id')
    op.drop_table('community_name')
    op.drop_table('community_description')
    # ### end Alembic commands ###
