class Code:
    SYSTEM_CATEGORY = 'system_category'
    CATEGORY_SELECTED = 'category_selected'
    ON_CONSIDERATION = 'on_consideration'
    VOTED = 'voted'
    ABSTAINED = 'abstained'
    REQUEST_SUCCESSFUL = 'request_successful'
    REQUEST_DENIED = 'request_denied'
    MEMBER_EXCLUDED = 'member_excluded'
    COMMUNITY_MEMBER = 'community_member'
    VOTED_BY_DEFAULT = 'voted_by_default'
    PRINCIPAL_AGREEMENT = 'principal_agreement'
    COMPROMISE = 'compromise'
    RULE_APPROVED = 'rule_approved'
    RULE_REVOKED = 'rule_revoked'
    NONCOMPLIANCE = 'noncompliance'
    INITIATIVE_APPROVED = 'initiative_approved'
    INITIATIVE_REVOKED = 'initiative_revoked'
